// ==================== Mini Español 词汇库 ====================
// 25 单元，1500+ 高频词，全部带例句
// 数据格式：{ es: "西语", zh: "中文", example: { es: "西语句子", zh: "中文翻译" } }

const UNITS = [
  // ============ Unit 1: 发音入门 ============
  {
    id: 1, title: "发音入门", emoji: "🗣️", color: "from-pink-500 to-rose-500", iconColor: "#FF4B4B",
    type: "pronunciation",
    tip: "西语发音很规则！每个字母基本只有一个读法。先学会字母和特殊音，以后看到单词就能读出来。",
    items: [
      { es: "a", zh: "元音 a", example: { es: "casa", zh: "房子" }, note: "类似中文「啊」" },
      { es: "e", zh: "元音 e", example: { es: "mesa", zh: "桌子" }, note: "类似「诶」，嘴稍张" },
      { es: "i", zh: "元音 i", example: { es: "misa", zh: "弥撒" }, note: "类似「衣」" },
      { es: "o", zh: "元音 o", example: { es: "boca", zh: "嘴" }, note: "类似「哦」，嘴圆" },
      { es: "u", zh: "元音 u", example: { es: "luna", zh: "月亮" }, note: "类似「乌」" },
      { es: "b", zh: "辅音 b", example: { es: "barco", zh: "船" }, note: "像中文「b」" },
      { es: "c", zh: "辅音 c (a/o/u)", example: { es: "casa", zh: "房子" }, note: "像「k」" },
      { es: "ce", zh: "辅音 ce/ci", example: { es: "cereza", zh: "樱桃" }, note: "像「se/the」" },
      { es: "d", zh: "辅音 d", example: { es: "día", zh: "天" }, note: "舌头抵上颚" },
      { es: "f", zh: "辅音 f", example: { es: "faro", zh: "灯塔" }, note: "上齿抵下唇" },
      { es: "g", zh: "辅音 g (a/o/u)", example: { es: "gato", zh: "猫" }, note: "像「g」" },
      { es: "ge", zh: "辅音 ge/gi", example: { es: "general", zh: "将军" }, note: "像「he」" },
      { es: "h", zh: "辅音 h", example: { es: "hola", zh: "你好" }, note: "永远不发音！" },
      { es: "j", zh: "辅音 j", example: { es: "joven", zh: "年轻" }, note: "喉咙发出的「h」" },
      { es: "l", zh: "辅音 l", example: { es: "luna", zh: "月亮" }, note: "舌尖抵上齿龈" },
      { es: "ll", zh: "辅音 ll", example: { es: "llave", zh: "钥匙" }, note: "像「y/lia」" },
      { es: "m", zh: "辅音 m", example: { es: "mamá", zh: "妈妈" }, note: "同英文" },
      { es: "n", zh: "辅音 n", example: { es: "niño", zh: "男孩" }, note: "同英文" },
      { es: "ñ", zh: "辅音 ñ", example: { es: "año", zh: "年" }, note: "像「nia」" },
      { es: "p", zh: "辅音 p", example: { es: "papá", zh: "爸爸" }, note: "送气比英文轻" },
      { es: "qu", zh: "辅音 qu", example: { es: "queso", zh: "奶酪" }, note: "像「k」，u 不发音" },
      { es: "r", zh: "辅音 r (词中)", example: { es: "pero", zh: "但是" }, note: "舌尖轻颤" },
      { es: "rr", zh: "辅音 rr (卷舌)", example: { es: "perro", zh: "狗" }, note: "用力卷舌！是西语特色" },
      { es: "s", zh: "辅音 s", example: { es: "sol", zh: "太阳" }, note: "同英文" },
      { es: "t", zh: "辅音 t", example: { es: "taza", zh: "杯子" }, note: "舌尖抵上齿" },
      { es: "v", zh: "辅音 v", example: { es: "vaca", zh: "牛" }, note: "和 b 几乎一样" },
      { es: "z", zh: "辅音 z", example: { es: "zapato", zh: "鞋子" }, note: "像「s/th」" },
      { es: "á", zh: "重音 á", example: { es: "está", zh: "他在" }, note: "重读这个音节" },
      { es: "é", zh: "重音 é", example: { es: "café", zh: "咖啡" }, note: "重读" },
      { es: "í", zh: "重音 í", example: { es: "aquí", zh: "这里" }, note: "重读" },
      { es: "ó", zh: "重音 ó", example: { es: "mató", zh: "他杀了" }, note: "重读" },
      { es: "ú", zh: "重音 ú", example: { es: "azúl", zh: "蓝色" }, note: "重读" }
    ]
  },

  // ============ Unit 2: 基础问候 ============
  {
    id: 2, title: "问候寒暄", emoji: "👋", color: "from-green-400 to-green-600", iconColor: "#58CC02",
    tip: "西语问候根据时间段不同用词也不同，是礼貌的第一课。",
    words: [
      { es: "Hola", zh: "你好", example: { es: "¡Hola! ¿Cómo estás?", zh: "你好！你好吗？" } },
      { es: "Adiós", zh: "再见", example: { es: "Adiós, hasta mañana.", zh: "再见，明天见。" } },
      { es: "Buenos días", zh: "早上好", example: { es: "Buenos días, profesor.", zh: "老师早上好。" } },
      { es: "Buenas tardes", zh: "下午好", example: { es: "Buenas tardes, señora.", zh: "女士下午好。" } },
      { es: "Buenas noches", zh: "晚上好/晚安", example: { es: "Buenas noches, mamá.", zh: "妈妈晚安。" } },
      { es: "Gracias", zh: "谢谢", example: { es: "Muchas gracias.", zh: "非常感谢。" } },
      { es: "Muchas gracias", zh: "非常感谢", example: { es: "Muchas gracias por todo.", zh: "非常感谢一切。" } },
      { es: "De nada", zh: "不客气", example: { es: "—Gracias. —De nada.", zh: "—谢谢。—不客气。" } },
      { es: "Por favor", zh: "请", example: { es: "Un café, por favor.", zh: "请来一杯咖啡。" } },
      { es: "Perdón", zh: "抱歉/借过", example: { es: "Perdón, ¿qué hora es?", zh: "请问几点了？" } },
      { es: "Lo siento", zh: "对不起", example: { es: "Lo siento mucho.", zh: "非常抱歉。" } },
      { es: "Sí", zh: "是", example: { es: "Sí, claro.", zh: "是的，当然。" } },
      { es: "No", zh: "不", example: { es: "No, gracias.", zh: "不，谢谢。" } },
      { es: "Tal vez", zh: "也许", example: { es: "Tal vez mañana.", zh: "也许明天。" } },
      { es: "Claro", zh: "当然", example: { es: "¡Claro que sí!", zh: "当然！" } },
      { es: "Por supuesto", zh: "当然", example: { es: "Por supuesto, amigo.", zh: "当然，朋友。" } },
      { es: "Cómo estás", zh: "你好吗", example: { es: "¿Cómo estás hoy?", zh: "今天怎么样？" } },
      { es: "Qué tal", zh: "怎么样", example: { es: "¿Qué tal?", zh: "怎么样？" } },
      { es: "Cómo te llamas", zh: "你叫什么", example: { es: "¿Cómo te llamas?", zh: "你叫什么名字？" } },
      { es: "Me llamo", zh: "我叫", example: { es: "Me llamo Ana.", zh: "我叫安娜。" } },
      { es: "Mucho gusto", zh: "很高兴认识你", example: { es: "Mucho gusto, Ana.", zh: "很高兴认识你，安娜。" } },
      { es: "Encantado", zh: "荣幸（男）", example: { es: "Encantado de conocerte.", zh: "很高兴认识你。" } },
      { es: "Encantada", zh: "荣幸（女）", example: { es: "Encantada, señor.", zh: "先生，幸会。" } },
      { es: "Igualmente", zh: "我也是", example: { es: "—Mucho gusto. —Igualmente.", zh: "—幸会。—我也是。" } },
      { es: "Hasta luego", zh: "回头见", example: { es: "Hasta luego, amigo.", zh: "回头见，朋友。" } },
      { es: "Hasta mañana", zh: "明天见", example: { es: "Hasta mañana, mamá.", zh: "明天见，妈妈。" } },
      { es: "Hasta pronto", zh: "很快见", example: { es: "Hasta pronto, cariño.", zh: "很快见，亲爱的。" } },
      { es: "Te quiero", zh: "我爱你（家人）", example: { es: "Te quiero, mamá.", zh: "我爱你，妈妈。" } },
      { es: "Te amo", zh: "我爱你（恋人）", example: { es: "Te amo, mi amor.", zh: "我爱你，我的爱人。" } },
      { es: "Te extraño", zh: "我想你", example: { es: "Te extraño mucho.", zh: "我很想你。" } }
    ]
  },

  // ============ Unit 3: 数字 ============
  {
    id: 3, title: "数字", emoji: "🔢", color: "from-blue-400 to-blue-600", iconColor: "#1CB0F6",
    tip: "西语数字 1-15 单独记忆，16+ 是组合规律：dieciséis (10+6)，veintiuno (20+1)。",
    words: [
      { es: "uno", zh: "一", example: { es: "Tengo uno.", zh: "我有一个。" } },
      { es: "dos", zh: "二", example: { es: "Dos gatos.", zh: "两只猫。" } },
      { es: "tres", zh: "三", example: { es: "Tres libros.", zh: "三本书。" } },
      { es: "cuatro", zh: "四", example: { es: "Cuatro amigos.", zh: "四个朋友。" } },
      { es: "cinco", zh: "五", example: { es: "Cinco minutos.", zh: "五分钟。" } },
      { es: "seis", zh: "六", example: { es: "Seis años.", zh: "六岁。" } },
      { es: "siete", zh: "七", example: { es: "Siete días.", zh: "七天。" } },
      { es: "ocho", zh: "八", example: { es: "Ocho meses.", zh: "八个月。" } },
      { es: "nueve", zh: "九", example: { es: "Nueve estrellas.", zh: "九颗星星。" } },
      { es: "diez", zh: "十", example: { es: "Diez dedos.", zh: "十根手指。" } },
      { es: "once", zh: "十一", example: { es: "Once jugadores.", zh: "十一个球员。" } },
      { es: "doce", zh: "十二", example: { es: "Doce meses.", zh: "十二个月。" } },
      { es: "trece", zh: "十三", example: { es: "Trece años.", zh: "十三岁。" } },
      { es: "catorce", zh: "十四", example: { es: "Catorce años.", zh: "十四岁。" } },
      { es: "quince", zh: "十五", example: { es: "Quince minutos.", zh: "十五分钟。" } },
      { es: "dieciséis", zh: "十六", example: { es: "Dieciséis años.", zh: "十六岁。" } },
      { es: "diecisiete", zh: "十七", example: { es: "Diecisiete años.", zh: "十七岁。" } },
      { es: "dieciocho", zh: "十八", example: { es: "Dieciocho años.", zh: "十八岁。" } },
      { es: "diecinueve", zh: "十九", example: { es: "Diecinueve años.", zh: "十九岁。" } },
      { es: "veinte", zh: "二十", example: { es: "Veinte euros.", zh: "二十欧元。" } },
      { es: "treinta", zh: "三十", example: { es: "Treinta minutos.", zh: "三十分钟。" } },
      { es: "cuarenta", zh: "四十", example: { es: "Cuarenta años.", zh: "四十岁。" } },
      { es: "cincuenta", zh: "五十", example: { es: "Cincuenta años.", zh: "五十岁。" } },
      { es: "sesenta", zh: "六十", example: { es: "Sesenta minutos.", zh: "六十分钟。" } },
      { es: "setenta", zh: "七十", example: { es: "Setenta años.", zh: "七十岁。" } },
      { es: "ochenta", zh: "八十", example: { es: "Ochenta años.", zh: "八十岁。" } },
      { es: "noventa", zh: "九十", example: { es: "Noventa años.", zh: "九十岁。" } },
      { es: "cien", zh: "一百", example: { es: "Cien euros.", zh: "一百欧元。" } },
      { es: "doscientos", zh: "两百", example: { es: "Doscientos kilómetros.", zh: "两百公里。" } },
      { es: "mil", zh: "一千", example: { es: "Mil gracias.", zh: "万分感谢。" } },
      { es: "millón", zh: "百万", example: { es: "Un millón de euros.", zh: "一百万欧元。" } },
      { es: "primero", zh: "第一", example: { es: "El primero de mayo.", zh: "五月一号。" } },
      { es: "segundo", zh: "第二", example: { es: "El segundo día.", zh: "第二天。" } },
      { es: "tercero", zh: "第三", example: { es: "El tercer piso.", zh: "三楼。" } },
      { es: "último", zh: "最后", example: { es: "El último tren.", zh: "最后一班火车。" } },
      { es: "mitad", zh: "一半", example: { es: "La mitad del pan.", zh: "半个面包。" } },
      { es: "doble", zh: "双倍", example: { es: "Doble ración.", zh: "双份。" } },
      { es: "par", zh: "双/偶数", example: { es: "Número par.", zh: "偶数。" } },
      { es: "docena", zh: "一打", example: { es: "Una docena de huevos.", zh: "一打鸡蛋。" } }
    ]
  },

  // ============ Unit 4: 颜色与形状 ============
  {
    id: 4, title: "颜色形状", emoji: "🌈", color: "from-pink-400 to-pink-600", iconColor: "#FF4B4B",
    tip: "颜色词作形容词时要和名词性数配合：el coche rojo（红色的车男单）。",
    words: [
      { es: "rojo", zh: "红色", example: { es: "El coche rojo.", zh: "红色的车。" } },
      { es: "azul", zh: "蓝色", example: { es: "El cielo azul.", zh: "蓝天。" } },
      { es: "verde", zh: "绿色", example: { es: "Hierba verde.", zh: "绿色的草。" } },
      { es: "amarillo", zh: "黄色", example: { es: "El sol amarillo.", zh: "黄色的太阳。" } },
      { es: "negro", zh: "黑色", example: { es: "Pelo negro.", zh: "黑色的头发。" } },
      { es: "blanco", zh: "白色", example: { es: "Nieve blanca.", zh: "白色的雪。" } },
      { es: "naranja", zh: "橙色", example: { es: "Zanahoria naranja.", zh: "橙色的胡萝卜。" } },
      { es: "rosa", zh: "粉色", example: { es: "Flores rosas.", zh: "粉色的花。" } },
      { es: "morado", zh: "紫色", example: { es: "Violeta morada.", zh: "紫色的紫罗兰。" } },
      { es: "marrón", zh: "棕色", example: { es: "Ojos marrones.", zh: "棕色的眼睛。" } },
      { es: "gris", zh: "灰色", example: { es: "Nubes grises.", zh: "灰色的云。" } },
      { es: "dorado", zh: "金色", example: { es: "Cabello dorado.", zh: "金色的头发。" } },
      { es: "plateado", zh: "银色", example: { es: "Luna plateada.", zh: "银色的月亮。" } },
      { es: "claro", zh: "浅/亮", example: { es: "Color claro.", zh: "浅色。" } },
      { es: "oscuro", zh: "深/暗", example: { es: "Azul oscuro.", zh: "深蓝色。" } },
      { es: "círculo", zh: "圆形", example: { es: "Un círculo rojo.", zh: "一个红色的圆。" } },
      { es: "cuadrado", zh: "正方形", example: { es: "Un cuadrado azul.", zh: "一个蓝色的正方形。" } },
      { es: "triángulo", zh: "三角形", example: { es: "Un triángulo verde.", zh: "一个绿色的三角形。" } },
      { es: "rectángulo", zh: "长方形", example: { es: "El rectángulo.", zh: "长方形。" } },
      { es: "estrella", zh: "星星", example: { es: "Una estrella brillante.", zh: "一颗闪亮的星。" } },
      { es: "corazón", zh: "心形", example: { es: "Un corazón rojo.", zh: "一颗红心。" } },
      { es: "línea", zh: "线", example: { es: "Una línea recta.", zh: "一条直线。" } },
      { es: "punto", zh: "点", example: { es: "Un punto rojo.", zh: "一个红点。" } },
      { es: "grande", zh: "大", example: { es: "Una casa grande.", zh: "一栋大房子。" } },
      { es: "pequeño", zh: "小", example: { es: "Un niño pequeño.", zh: "一个小孩。" } },
      { es: "alto", zh: "高", example: { es: "Un hombre alto.", zh: "一个高个子男人。" } },
      { es: "bajo", zh: "矮/低", example: { es: "Un edificio bajo.", zh: "一栋矮楼。" } },
      { es: "largo", zh: "长", example: { es: "Pelo largo.", zh: "长发。" } },
      { es: "corto", zh: "短", example: { es: "Pelo corto.", zh: "短发。" } },
      { es: "ancho", zh: "宽", example: { es: "Calle ancha.", zh: "宽街。" } },
      { es: "estrecho", zh: "窄", example: { es: "Calle estrecha.", zh: "窄街。" } }
    ]
  },

  // ============ Unit 5: 时间与日期 ============
  {
    id: 5, title: "时间日期", emoji: "⏰", color: "from-indigo-400 to-indigo-600", iconColor: "#1CB0F6",
    tip: "西语星期和月份都不大写。月份多数以 -o 结尾。",
    words: [
      { es: "tiempo", zh: "时间", example: { es: "No tengo tiempo.", zh: "我没有时间。" } },
      { es: "hora", zh: "小时/点钟", example: { es: "¿Qué hora es?", zh: "几点了？" } },
      { es: "minuto", zh: "分钟", example: { es: "Un minuto, por favor.", zh: "请等一分钟。" } },
      { es: "segundo", zh: "秒", example: { es: "Un segundo.", zh: "一秒钟。" } },
      { es: "día", zh: "天/日", example: { es: "Buen día.", zh: "美好的一天。" } },
      { es: "semana", zh: "周", example: { es: "Una semana.", zh: "一周。" } },
      { es: "mes", zh: "月", example: { es: "Este mes.", zh: "这个月。" } },
      { es: "año", zh: "年", example: { es: "Un año.", zh: "一年。" } },
      { es: "hoy", zh: "今天", example: { es: "Hoy es lunes.", zh: "今天是周一。" } },
      { es: "ayer", zh: "昨天", example: { es: "Ayer fue domingo.", zh: "昨天是周日。" } },
      { es: "mañana", zh: "明天/早晨", example: { es: "Mañana es martes.", zh: "明天是周二。" } },
      { es: "anteayer", zh: "前天", example: { es: "Anteayer llovió.", zh: "前天下雨了。" } },
      { es: "ahora", zh: "现在", example: { es: "Ahora no.", zh: "现在不行。" } },
      { es: "después", zh: "之后", example: { es: "Después de comer.", zh: "吃完饭后。" } },
      { es: "antes", zh: "之前", example: { es: "Antes de dormir.", zh: "睡前。" } },
      { es: "siempre", zh: "总是", example: { es: "Siempre temprano.", zh: "总是早。" } },
      { es: "nunca", zh: "从不", example: { es: "Nunca digo mentiras.", zh: "我从不撒谎。" } },
      { es: "a veces", zh: "有时", example: { es: "A veces leo.", zh: "有时我读书。" } },
      { es: "lunes", zh: "周一", example: { es: "El lunes voy al colegio.", zh: "周一我去学校。" } },
      { es: "martes", zh: "周二", example: { es: "Martes y trece.", zh: "周二又十三号。" } },
      { es: "miércoles", zh: "周三", example: { es: "El miércoles tengo clase.", zh: "周三我有课。" } },
      { es: "jueves", zh: "周四", example: { es: "Jueves de español.", zh: "西语周四。" } },
      { es: "viernes", zh: "周五", example: { es: "¡Por fin viernes!", zh: "终于到周五了！" } },
      { es: "sábado", zh: "周六", example: { es: "El sábado descanso.", zh: "周六我休息。" } },
      { es: "domingo", zh: "周日", example: { es: "Domingo de paseo.", zh: "周日散步。" } },
      { es: "enero", zh: "一月", example: { es: "Enero es frío.", zh: "一月很冷。" } },
      { es: "febrero", zh: "二月", example: { es: "Febrero corto.", zh: "二月短。" } },
      { es: "marzo", zh: "三月", example: { es: "Marzo ventoso.", zh: "三月多风。" } },
      { es: "abril", zh: "四月", example: { es: "Abril lluvioso.", zh: "四月多雨。" } },
      { es: "mayo", zh: "五月", example: { es: "Mayo florido.", zh: "五月花开。" } },
      { es: "junio", zh: "六月", example: { es: "Junio caluroso.", zh: "六月炎热。" } },
      { es: "julio", zh: "七月", example: { es: "Julio de verano.", zh: "夏季的七月。" } },
      { es: "agosto", zh: "八月", example: { es: "Agosto de vacaciones.", zh: "八月度假。" } },
      { es: "septiembre", zh: "九月", example: { es: "Septiembre escolar.", zh: "九月开学。" } },
      { es: "octubre", zh: "十月", example: { es: "Octubre dorado.", zh: "金色的十月。" } },
      { es: "noviembre", zh: "十一月", example: { es: "Noviembre gris.", zh: "灰蒙蒙的十一月。" } },
      { es: "diciembre", zh: "十二月", example: { es: "Diciembre frío.", zh: "十二月冷。" } },
      { es: "mañana", zh: "早晨", example: { es: "Por la mañana.", zh: "早上。" } },
      { es: "tarde", zh: "下午", example: { es: "Por la tarde.", zh: "下午。" } },
      { es: "noche", zh: "夜晚", example: { es: "Por la noche.", zh: "夜里。" } },
      { es: "mediodía", zh: "中午", example: { es: "Al mediodía.", zh: "中午。" } },
      { es: "medianoche", zh: "午夜", example: { es: "A medianoche.", zh: "午夜时分。" } },
      { es: "temprano", zh: "早", example: { es: "Llego temprano.", zh: "我到得早。" } },
      { es: "tarde", zh: "晚（迟）", example: { es: "Llego tarde.", zh: "我迟到了。" } }
    ]
  },

  // ============ Unit 6: 家庭 ============
  {
    id: 6, title: "家庭关系", emoji: "👨‍👩‍👧", color: "from-rose-400 to-rose-600", iconColor: "#FF4B4B",
    tip: "西语家庭成员词男女成对：hermano/hermana。Mi = 我的，Tu = 你的。",
    words: [
      { es: "familia", zh: "家庭", example: { es: "Mi familia.", zh: "我的家。" } },
      { es: "mamá", zh: "妈妈", example: { es: "Mi mamá cocina.", zh: "我妈妈做饭。" } },
      { es: "papá", zh: "爸爸", example: { es: "Papá trabaja.", zh: "爸爸工作。" } },
      { es: "madre", zh: "母亲", example: { es: "Día de la madre.", zh: "母亲节。" } },
      { es: "padre", zh: "父亲", example: { es: "Mi padre.", zh: "我父亲。" } },
      { es: "hermano", zh: "兄弟", example: { es: "Mi hermano mayor.", zh: "我的哥哥。" } },
      { es: "hermana", zh: "姐妹", example: { es: "Mi hermana menor.", zh: "我的妹妹。" } },
      { es: "hijo", zh: "儿子", example: { es: "Mi hijo.", zh: "我的儿子。" } },
      { es: "hija", zh: "女儿", example: { es: "Mi hija Ana.", zh: "我女儿安娜。" } },
      { es: "hijos", zh: "孩子们", example: { es: "Mis hijos.", zh: "我的孩子们。" } },
      { es: "abuelo", zh: "爷爷/外公", example: { es: "Mi abuelo.", zh: "我爷爷。" } },
      { es: "abuela", zh: "奶奶/外婆", example: { es: "Mi abuela cocina.", zh: "我奶奶做饭。" } },
      { es: "abuelos", zh: "祖父母", example: { es: "Mis abuelos.", zh: "我的祖父母。" } },
      { es: "nieto", zh: "孙子/外孙", example: { es: "El nieto.", zh: "孙子。" } },
      { es: "nieta", zh: "孙女/外孙女", example: { es: "La nieta.", zh: "孙女。" } },
      { es: "tío", zh: "叔叔/舅舅", example: { es: "Mi tío Juan.", zh: "我叔叔胡安。" } },
      { es: "tía", zh: "阿姨/姑姑", example: { es: "Mi tía María.", zh: "我阿姨玛丽亚。" } },
      { es: "primo", zh: "堂/表兄弟", example: { es: "Mi primo Pedro.", zh: "我表哥佩德罗。" } },
      { es: "prima", zh: "堂/表姐妹", example: { es: "Mi prima Ana.", zh: "我表姐安娜。" } },
      { es: "sobrino", zh: "侄子/外甥", example: { es: "Mi sobrino.", zh: "我外甥。" } },
      { es: "sobrina", zh: "侄女/外甥女", example: { es: "Mi sobrina.", zh: "我外甥女。" } },
      { es: "esposo", zh: "丈夫", example: { es: "Mi esposo.", zh: "我丈夫。" } },
      { es: "esposa", zh: "妻子", example: { es: "Mi esposa.", zh: "我妻子。" } },
      { es: "novio", zh: "男朋友", example: { es: "Mi novio.", zh: "我男朋友。" } },
      { es: "novia", zh: "女朋友", example: { es: "Mi novia.", zh: "我女朋友。" } },
      { es: "bebé", zh: "宝宝", example: { es: "Un bebé.", zh: "一个宝宝。" } },
      { es: "niño", zh: "男孩", example: { es: "Un niño.", zh: "一个男孩。" } },
      { es: "niña", zh: "女孩", example: { es: "Una niña.", zh: "一个女孩。" } },
      { es: "hombre", zh: "男人", example: { es: "Un hombre.", zh: "一个男人。" } },
      { es: "mujer", zh: "女人", example: { es: "Una mujer.", zh: "一个女人。" } },
      { es: "amigo", zh: "朋友（男）", example: { es: "Mi amigo.", zh: "我朋友。" } },
      { es: "amiga", zh: "朋友（女）", example: { es: "Mi amiga.", zh: "我朋友。" } },
      { es: "suegro", zh: "岳父/公公", example: { es: "Mi suegro.", zh: "我岳父。" } },
      { es: "suegra", zh: "岳母/婆婆", example: { es: "Mi suegra.", zh: "我岳母。" } },
      { es: "cuñado", zh: "姐夫/妹夫", example: { es: "Mi cuñado.", zh: "我姐夫。" } },
      { es: "cuñada", zh: "嫂子/弟妹", example: { es: "Mi cuñada.", zh: "我嫂子。" } }
    ]
  },

  // ============ Unit 7: 身体部位 ============
  {
    id: 7, title: "身体部位", emoji: "👃", color: "from-purple-400 to-purple-600", iconColor: "#CE82FF",
    tip: "身体部位词多带定冠词：Tengo dolor de cabeza (我头疼)。",
    words: [
      { es: "cabeza", zh: "头", example: { es: "Me duele la cabeza.", zh: "我头疼。" } },
      { es: "cara", zh: "脸", example: { es: "Mi cara.", zh: "我的脸。" } },
      { es: "frente", zh: "额头", example: { es: "La frente.", zh: "额头。" } },
      { es: "ojo", zh: "眼睛", example: { es: "Ojos azules.", zh: "蓝色的眼睛。" } },
      { es: "ojos", zh: "眼睛（复）", example: { es: "Mis ojos.", zh: "我的眼睛。" } },
      { es: "ceja", zh: "眉毛", example: { es: "Las cejas.", zh: "眉毛。" } },
      { es: "pestaña", zh: "睫毛", example: { es: "Pestañas largas.", zh: "长睫毛。" } },
      { es: "nariz", zh: "鼻子", example: { es: "Nariz grande.", zh: "大鼻子。" } },
      { es: "boca", zh: "嘴巴", example: { es: "Boca abierta.", zh: "张开的嘴。" } },
      { es: "labio", zh: "嘴唇", example: { es: "Labios rosados.", zh: "粉红色的嘴唇。" } },
      { es: "diente", zh: "牙齿", example: { es: "Diente blanco.", zh: "白牙。" } },
      { es: "lengua", zh: "舌头", example: { es: "La lengua.", zh: "舌头。" } },
      { es: "oreja", zh: "耳朵", example: { es: "Oreja pequeña.", zh: "小耳朵。" } },
      { es: "oído", zh: "听觉/内耳", example: { es: "Dolor de oído.", zh: "耳朵疼。" } },
      { es: "pelo", zh: "头发", example: { es: "Pelo largo.", zh: "长发。" } },
      { es: "cabello", zh: "头发（书）", example: { es: "Cabello rubio.", zh: "金发。" } },
      { es: "cuello", zh: "脖子", example: { es: "Cuello largo.", zh: "长脖子。" } },
      { es: "hombro", zh: "肩膀", example: { es: "Hombros anchos.", zh: "宽肩膀。" } },
      { es: "brazo", zh: "手臂", example: { es: "Brazo fuerte.", zh: "强壮的手臂。" } },
      { es: "codo", zh: "肘", example: { es: "El codo.", zh: "肘部。" } },
      { es: "muñeca", zh: "手腕", example: { es: "La muñeca.", zh: "手腕。" } },
      { es: "mano", zh: "手", example: { es: "Dame la mano.", zh: "把手给我。" } },
      { es: "dedo", zh: "手指", example: { es: "Dedo índice.", zh: "食指。" } },
      { es: "dedo gordo", zh: "大拇指", example: { es: "Dedo gordo.", zh: "大拇指。" } },
      { es: "uña", zh: "指甲", example: { es: "Uñas largas.", zh: "长指甲。" } },
      { es: "pecho", zh: "胸", example: { es: "Dolor de pecho.", zh: "胸痛。" } },
      { es: "espalda", zh: "背", example: { es: "Dolor de espalda.", zh: "背痛。" } },
      { es: "cintura", zh: "腰", example: { es: "Cintura fina.", zh: "细腰。" } },
      { es: "cadera", zh: "髋", example: { es: "Las caderas.", zh: "髋部。" } },
      { es: "pierna", zh: "腿", example: { es: "Pierna larga.", zh: "长腿。" } },
      { es: "rodilla", zh: "膝盖", example: { es: "Rodilla rota.", zh: "膝盖受伤。" } },
      { es: "tobillo", zh: "脚踝", example: { es: "Tobillo hinchado.", zh: "脚踝肿。" } },
      { es: "pie", zh: "脚", example: { es: "Pie derecho.", zh: "右脚。" } },
      { es: "talón", zh: "脚后跟", example: { es: "El talón.", zh: "脚后跟。" } },
      { es: "corazón", zh: "心脏", example: { es: "Mi corazón.", zh: "我的心。" } },
      { es: "estómago", zh: "胃", example: { es: "Dolor de estómago.", zh: "胃痛。" } }
    ]
  },

  // ============ Unit 8: 食物与饮料 ============
  {
    id: 8, title: "食物饮料", emoji: "🍎", color: "from-yellow-400 to-yellow-600", iconColor: "#FFC800",
    tip: "点餐用 Quiero + 食物（我想要）。Me gusta + 食物（我喜欢）。",
    words: [
      { es: "comida", zh: "食物/餐", example: { es: "La comida está rica.", zh: "饭很好吃。" } },
      { es: "desayuno", zh: "早餐", example: { es: "El desayuno.", zh: "早餐。" } },
      { es: "almuerzo", zh: "午餐", example: { es: "El almuerzo.", zh: "午餐。" } },
      { es: "cena", zh: "晚餐", example: { es: "La cena.", zh: "晚餐。" } },
      { es: "agua", zh: "水", example: { es: "Quiero agua.", zh: "我想要水。" } },
      { es: "pan", zh: "面包", example: { es: "Pan fresco.", zh: "新鲜的面包。" } },
      { es: "leche", zh: "牛奶", example: { es: "Leche con café.", zh: "加咖啡的牛奶。" } },
      { es: "café", zh: "咖啡", example: { es: "Un café, por favor.", zh: "请来一杯咖啡。" } },
      { es: "té", zh: "茶", example: { es: "Té verde.", zh: "绿茶。" } },
      { es: "zumo", zh: "果汁", example: { es: "Zumo de naranja.", zh: "橙汁。" } },
      { es: "jugo", zh: "果汁（拉美）", example: { es: "Jugo de manzana.", zh: "苹果汁。" } },
      { es: "arroz", zh: "米饭", example: { es: "Arroz con pollo.", zh: "鸡肉饭。" } },
      { es: "fideos", zh: "面条", example: { es: "Fideos chinos.", zh: "中式面条。" } },
      { es: "sopa", zh: "汤", example: { es: "Sopa de pollo.", zh: "鸡汤。" } },
      { es: "ensalada", zh: "沙拉", example: { es: "Ensalada mixta.", zh: "混合沙拉。" } },
      { es: "carne", zh: "肉", example: { es: "Carne de res.", zh: "牛肉。" } },
      { es: "pollo", zh: "鸡肉", example: { es: "Pollo asado.", zh: "烤鸡。" } },
      { es: "cerdo", zh: "猪肉", example: { es: "Chuleta de cerdo.", zh: "猪排。" } },
      { es: "cordero", zh: "羊肉", example: { es: "Cordero asado.", zh: "烤羊肉。" } },
      { es: "pescado", zh: "鱼（食用）", example: { es: "Pescado frito.", zh: "炸鱼。" } },
      { es: "marisco", zh: "海鲜", example: { es: "Marisco fresco.", zh: "新鲜海鲜。" } },
      { es: "camarón", zh: "虾", example: { es: "Camarones.", zh: "虾。" } },
      { es: "queso", zh: "奶酪", example: { es: "Queso manchego.", zh: "曼彻格奶酪。" } },
      { es: "mantequilla", zh: "黄油", example: { es: "Mantequilla con pan.", zh: "黄油配面包。" } },
      { es: "huevo", zh: "鸡蛋", example: { es: "Huevos revueltos.", zh: "炒蛋。" } },
      { es: "tortilla", zh: "鸡蛋饼/玉米饼", example: { es: "Tortilla española.", zh: "西班牙蛋饼。" } },
      { es: "azúcar", zh: "糖", example: { es: "Sin azúcar.", zh: "不加糖。" } },
      { es: "sal", zh: "盐", example: { es: "Un poco de sal.", zh: "一点盐。" } },
      { es: "aceite", zh: "油", example: { es: "Aceite de oliva.", zh: "橄榄油。" } },
      { es: "vinagre", zh: "醋", example: { es: "Vinagre balsámico.", zh: "香醋。" } },
      { es: "ajo", zh: "大蒜", example: { es: "Ajo picado.", zh: "蒜末。" } },
      { es: "cebolla", zh: "洋葱", example: { es: "Cebolla blanca.", zh: "白洋葱。" } },
      { es: "tomate", zh: "西红柿", example: { es: "Tomate rojo.", zh: "红番茄。" } },
      { es: "patata", zh: "土豆", example: { es: "Patatas fritas.", zh: "炸薯条。" } },
      { es: "arroz", zh: "米", example: { es: "Arroz blanco.", zh: "白米饭。" } },
      { es: "pasta", zh: "意面", example: { es: "Pasta italiana.", zh: "意大利面。" } },
      { es: "pizza", zh: "披萨", example: { es: "Una pizza.", zh: "一个披萨。" } },
      { es: "hamburguesa", zh: "汉堡", example: { es: "Hamburguesa con queso.", zh: "奶酪汉堡。" } },
      { es: "sándwich", zh: "三明治", example: { es: "Un sándwich.", zh: "一个三明治。" } },
      { es: "helado", zh: "冰淇淋", example: { es: "Helado de chocolate.", zh: "巧克力冰淇淋。" } },
      { es: "pastel", zh: "蛋糕", example: { es: "Pastel de cumpleaños.", zh: "生日蛋糕。" } },
      { es: "galleta", zh: "饼干", example: { es: "Galletas de chocolate.", zh: "巧克力饼干。" } },
      { es: "chocolate", zh: "巧克力", example: { es: "Chocolate negro.", zh: "黑巧克力。" } },
      { es: "caramelo", zh: "糖果", example: { es: "Un caramelo.", zh: "一颗糖。" } },
      { es: "mermelada", zh: "果酱", example: { es: "Mermelada de fresa.", zh: "草莓酱。" } },
      { es: "miel", zh: "蜂蜜", example: { es: "Miel natural.", zh: "天然蜂蜜。" } }
    ]
  },

  // ============ Unit 9: 水果蔬菜 ============
  {
    id: 9, title: "水果蔬菜", emoji: "🥕", color: "from-green-400 to-emerald-600", iconColor: "#58CC02",
    tip: "西语水果多以 -a 结尾。el agua (f.) 是阴性但用 el，因为是重音 a 开头。",
    words: [
      { es: "fruta", zh: "水果", example: { es: "Fruta fresca.", zh: "新鲜水果。" } },
      { es: "manzana", zh: "苹果", example: { es: "Manzana roja.", zh: "红苹果。" } },
      { es: "plátano", zh: "香蕉", example: { es: "Plátano amarillo.", zh: "黄香蕉。" } },
      { es: "naranja", zh: "橙子", example: { es: "Naranja dulce.", zh: "甜橙子。" } },
      { es: "mandarina", zh: "橘子", example: { es: "Mandarina dulce.", zh: "甜橘子。" } },
      { es: "limón", zh: "柠檬", example: { es: "Limón amarillo.", zh: "黄柠檬。" } },
      { es: "fresa", zh: "草莓", example: { es: "Fresas con crema.", zh: "奶油草莓。" } },
      { es: "frutilla", zh: "草莓（拉美）", example: { es: "Frutillas frescas.", zh: "新鲜草莓。" } },
      { es: "uva", zh: "葡萄", example: { es: "Uvas verdes.", zh: "青葡萄。" } },
      { es: "pera", zh: "梨", example: { es: "Pera dulce.", zh: "甜梨。" } },
      { es: "durazno", zh: "桃子", example: { es: "Durazno maduro.", zh: "熟桃子。" } },
      { es: "melocotón", zh: "桃（西）", example: { es: "Melocotón jugoso.", zh: "多汁的桃。" } },
      { es: "cereza", zh: "樱桃", example: { es: "Cerezas rojas.", zh: "红樱桃。" } },
      { es: "ciruela", zh: "李子", example: { es: "Ciruela morada.", zh: "紫李子。" } },
      { es: "sandía", zh: "西瓜", example: { es: "Sandía dulce.", zh: "甜西瓜。" } },
      { es: "melón", zh: "哈密瓜", example: { es: "Melón maduro.", zh: "熟哈密瓜。" } },
      { es: "piña", zh: "菠萝", example: { es: "Piña tropical.", zh: "热带菠萝。" } },
      { es: "mango", zh: "芒果", example: { es: "Mango dulce.", zh: "甜芒果。" } },
      { es: "papaya", zh: "木瓜", example: { es: "Papaya tropical.", zh: "热带木瓜。" } },
      { es: "coco", zh: "椰子", example: { es: "Coco fresco.", zh: "新鲜椰子。" } },
      { es: "kiwi", zh: "猕猴桃", example: { es: "Kiwi verde.", zh: "绿猕猴桃。" } },
      { es: "granada", zh: "石榴", example: { es: "Granada roja.", zh: "红石榴。" } },
      { es: "higo", zh: "无花果", example: { es: "Higos dulces.", zh: "甜无花果。" } },
      { es: "dátil", zh: "枣", example: { es: "Dátiles dulces.", zh: "甜枣。" } },
      { es: "verdura", zh: "蔬菜", example: { es: "Verduras frescas.", zh: "新鲜蔬菜。" } },
      { es: "zanahoria", zh: "胡萝卜", example: { es: "Zanahoria naranja.", zh: "橙胡萝卜。" } },
      { es: "papa", zh: "土豆（拉美）", example: { es: "Papas fritas.", zh: "炸薯条。" } },
      { es: "patata", zh: "土豆（西）", example: { es: "Patatas.", zh: "土豆。" } },
      { es: "brócoli", zh: "西兰花", example: { es: "Brócoli verde.", zh: "绿西兰花。" } },
      { es: "coliflor", zh: "花椰菜", example: { es: "Coliflor blanca.", zh: "白花椰菜。" } },
      { es: "lechuga", zh: "生菜", example: { es: "Lechuga fresca.", zh: "新鲜生菜。" } },
      { es: "pepino", zh: "黄瓜", example: { es: "Pepino verde.", zh: "绿黄瓜。" } },
      { es: "pimiento", zh: "辣椒/彩椒", example: { es: "Pimiento rojo.", zh: "红椒。" } },
      { es: "calabacín", zh: "西葫芦", example: { es: "Calabacín verde.", zh: "绿西葫芦。" } },
      { es: "calabaza", zh: "南瓜", example: { es: "Calabaza naranja.", zh: "橙南瓜。" } },
      { es: "maíz", zh: "玉米", example: { es: "Maíz dulce.", zh: "甜玉米。" } },
      { es: "guisante", zh: "豌豆", example: { es: "Guisantes verdes.", zh: "青豌豆。" } },
      { es: "fresa", zh: "草莓", example: { es: "Fresas.", zh: "草莓。" } },
      { es: "ajo", zh: "蒜", example: { es: "Diente de ajo.", zh: "一瓣蒜。" } },
      { es: "espinaca", zh: "菠菜", example: { es: "Espinacas.", zh: "菠菜。" } },
      { es: "champiñón", zh: "蘑菇", example: { es: "Champiñones.", zh: "蘑菇。" } }
    ]
  },

  // ============ Unit 10: 动物世界 ============
  {
    id: 10, title: "动物世界", emoji: "🐶", color: "from-orange-400 to-orange-600", iconColor: "#FF9600",
    tip: "西语动物词男女有别：el gato（公猫）/ la gata（母猫）。elefante 不分。",
    words: [
      { es: "animal", zh: "动物", example: { es: "Los animales.", zh: "动物们。" } },
      { es: "perro", zh: "狗", example: { es: "Mi perro es grande.", zh: "我的狗很大。" } },
      { es: "perra", zh: "母狗", example: { es: "La perra.", zh: "母狗。" } },
      { es: "gato", zh: "猫", example: { es: "El gato duerme.", zh: "猫在睡觉。" } },
      { es: "gata", zh: "母猫", example: { es: "La gata.", zh: "母猫。" } },
      { es: "pájaro", zh: "鸟", example: { es: "Un pájaro canta.", zh: "一只鸟在唱歌。" } },
      { es: "pájaro", zh: "鸟", example: { es: "Pájaros volando.", zh: "飞鸟。" } },
      { es: "pez", zh: "鱼", example: { es: "El pez nada.", zh: "鱼在游。" } },
      { es: "caballo", zh: "马", example: { es: "Caballo rápido.", zh: "快马。" } },
      { es: "yegua", zh: "母马", example: { es: "La yegua.", zh: "母马。" } },
      { es: "vaca", zh: "奶牛", example: { es: "La vaca da leche.", zh: "牛产奶。" } },
      { es: "toro", zh: "公牛", example: { es: "El toro bravo.", zh: "勇猛的公牛。" } },
      { es: "oveja", zh: "绵羊", example: { es: "Ovejas blancas.", zh: "白绵羊。" } },
      { es: "cabra", zh: "山羊", example: { es: "La cabra.", zh: "山羊。" } },
      { es: "cerdo", zh: "猪", example: { es: "Cerdo rosado.", zh: "粉色的猪。" } },
      { es: "conejo", zh: "兔子", example: { es: "Conejo blanco.", zh: "白兔。" } },
      { es: "ratón", zh: "老鼠", example: { es: "Un ratón.", zh: "一只老鼠。" } },
      { es: "conejo", zh: "兔子", example: { es: "Conejo saltarín.", zh: "跳跳兔。" } },
      { es: "león", zh: "狮子", example: { es: "El león ruge.", zh: "狮子在吼。" } },
      { es: "leona", zh: "母狮", example: { es: "La leona.", zh: "母狮。" } },
      { es: "tigre", zh: "老虎", example: { es: "El tigre.", zh: "老虎。" } },
      { es: "elefante", zh: "大象", example: { es: "Elefante grande.", zh: "大象很大。" } },
      { es: "elefanta", zh: "母象", example: { es: "La elefanta.", zh: "母象。" } },
      { es: "jirafa", zh: "长颈鹿", example: { es: "Jirafa alta.", zh: "高高的长颈鹿。" } },
      { es: "cebra", zh: "斑马", example: { es: "Cebra rayada.", zh: "条纹斑马。" } },
      { es: "mono", zh: "猴子", example: { es: "Mono travieso.", zh: "淘气的猴子。" } },
      { es: "mona", zh: "母猴", example: { es: "La mona.", zh: "母猴。" } },
      { es: "oso", zh: "熊", example: { es: "Oso pardo.", zh: "棕熊。" } },
      { es: "osa", zh: "母熊", example: { es: "La osa.", zh: "母熊。" } },
      { es: "lobo", zh: "狼", example: { es: "Lobo gris.", zh: "灰狼。" } },
      { es: "loba", zh: "母狼", example: { es: "La loba.", zh: "母狼。" } },
      { es: "zorro", zh: "狐狸", example: { es: "Zorro rojo.", zh: "红狐。" } },
      { es: "águila", zh: "鹰", example: { es: "El águila vuela.", zh: "鹰在飞。" } },
      { es: "búho", zh: "猫头鹰", example: { es: "Búho nocturno.", zh: "夜行猫头鹰。" } },
      { es: "pato", zh: "鸭子", example: { es: "Pato en el agua.", zh: "水里的鸭子。" } },
      { es: "gallina", zh: "母鸡", example: { es: "La gallina pone huevos.", zh: "母鸡下蛋。" } },
      { es: "gallo", zh: "公鸡", example: { es: "El gallo canta.", zh: "公鸡打鸣。" } },
      { es: "cisne", zh: "天鹅", example: { es: "Cisne blanco.", zh: "白天鹅。" } },
      { es: "mariposa", zh: "蝴蝶", example: { es: "Mariposa colorida.", zh: "彩色的蝴蝶。" } },
      { es: "abeja", zh: "蜜蜂", example: { es: "Una abeja.", zh: "一只蜜蜂。" } },
      { es: "araña", zh: "蜘蛛", example: { es: "Araña pequeña.", zh: "小蜘蛛。" } },
      { es: "gusano", zh: "虫子", example: { es: "Un gusano.", zh: "一条虫子。" } },
      { es: "pez", zh: "鱼", example: { es: "Pez de colores.", zh: "彩色的鱼。" } },
      { es: "tiburón", zh: "鲨鱼", example: { es: "Tiburón peligroso.", zh: "危险的鲨鱼。" } },
      { es: "delfín", zh: "海豚", example: { es: "Delfín juguetón.", zh: "爱玩的海豚。" } },
      { es: "ballena", zh: "鲸鱼", example: { es: "Ballena enorme.", zh: "巨大的鲸鱼。" } },
      { es: "pulpo", zh: "章鱼", example: { es: "Un pulpo.", zh: "一只章鱼。" } },
      { es: "cangrejo", zh: "螃蟹", example: { es: "Cangrejo rojo.", zh: "红螃蟹。" } },
      { es: "rana", zh: "青蛙", example: { es: "Rana verde.", zh: "绿青蛙。" } },
      { es: "serpiente", zh: "蛇", example: { es: "Serpiente larga.", zh: "长蛇。" } },
      { es: "tortuga", zh: "乌龟", example: { es: "Tortuga lenta.", zh: "慢乌龟。" } },
      { es: "lagartija", zh: "蜥蜴", example: { es: "Lagartija pequeña.", zh: "小蜥蜴。" } },
      { es: "murciélago", zh: "蝙蝠", example: { es: "Murciélago nocturno.", zh: "夜行的蝙蝠。" } }
    ]
  },

  // ============ Unit 11: 衣物配饰 ============
  {
    id: 11, title: "衣物配饰", emoji: "👕", color: "from-cyan-400 to-cyan-600", iconColor: "#1CB0F6",
    tip: "穿戴动词常用 Llevo (我穿/戴) + 衣物。脱下用 Quitarse。",
    words: [
      { es: "ropa", zh: "衣服", example: { es: "Ropa nueva.", zh: "新衣服。" } },
      { es: "camisa", zh: "衬衫", example: { es: "Camisa blanca.", zh: "白衬衫。" } },
      { es: "camiseta", zh: "T恤", example: { es: "Camiseta azul.", zh: "蓝T恤。" } },
      { es: "pantalón", zh: "裤子", example: { es: "Pantalón azul.", zh: "蓝裤子。" } },
      { es: "pantalones", zh: "裤子（复）", example: { es: "Pantalones cortos.", zh: "短裤。" } },
      { es: "vaqueros", zh: "牛仔裤", example: { es: "Vaqueros rotos.", zh: "破洞牛仔裤。" } },
      { es: "jeans", zh: "牛仔裤", example: { es: "Jeans azules.", zh: "蓝牛仔。" } },
      { es: "falda", zh: "裙子", example: { es: "Falda rosa.", zh: "粉裙子。" } },
      { es: "vestido", zh: "连衣裙", example: { es: "Vestido bonito.", zh: "漂亮的连衣裙。" } },
      { es: "zapato", zh: "鞋", example: { es: "Zapatos nuevos.", zh: "新鞋。" } },
      { es: "zapatos", zh: "鞋（复）", example: { es: "Zapatos negros.", zh: "黑鞋。" } },
      { es: "zapatilla", zh: "运动鞋", example: { es: "Zapatillas blancas.", zh: "白运动鞋。" } },
      { es: "tenis", zh: "网球鞋", example: { es: "Tenis nuevos.", zh: "新球鞋。" } },
      { es: "bota", zh: "靴子", example: { es: "Botas de lluvia.", zh: "雨靴。" } },
      { es: "sandalia", zh: "凉鞋", example: { es: "Sandalias de verano.", zh: "夏季凉鞋。" } },
      { es: "calcetín", zh: "袜子", example: { es: "Calcetines blancos.", zh: "白袜子。" } },
      { es: "calcetines", zh: "袜子（复）", example: { es: "Mis calcetines.", zh: "我的袜子。" } },
      { es: "medias", zh: "长袜", example: { es: "Medias de nylon.", zh: "尼龙长袜。" } },
      { es: "chaqueta", zh: "外套", example: { es: "Chaqueta de invierno.", zh: "冬外套。" } },
      { es: "abrigo", zh: "大衣", example: { es: "Abrigo grueso.", zh: "厚大衣。" } },
      { es: "suéter", zh: "毛衣", example: { es: "Suéter de lana.", zh: "羊毛衫。" } },
      { es: "jersey", zh: "针织衫", example: { es: "Jersey azul.", zh: "蓝针织衫。" } },
      { es: "blusa", zh: "女衬衫", example: { es: "Blusa blanca.", zh: "白女衬衫。" } },
      { es: "corbata", zh: "领带", example: { es: "Corbata roja.", zh: "红领带。" } },
      { es: "cinturón", zh: "腰带", example: { es: "Cinturón de cuero.", zh: "皮带。" } },
      { es: "bolso", zh: "包/手提包", example: { es: "Bolso de mano.", zh: "手提包。" } },
      { es: "mochila", zh: "背包", example: { es: "Mochila escolar.", zh: "书包。" } },
      { es: "cartera", zh: "钱包", example: { es: "Cartera de piel.", zh: "皮钱包。" } },
      { es: "sombrero", zh: "帽子", example: { es: "Sombrero grande.", zh: "大帽子。" } },
      { es: "gorra", zh: "棒球帽", example: { es: "Gorra deportiva.", zh: "运动帽。" } },
      { es: "gorro", zh: "毛线帽", example: { es: "Gorro de lana.", zh: "毛线帽。" } },
      { es: "bufanda", zh: "围巾", example: { es: "Bufanda roja.", zh: "红围巾。" } },
      { es: "guantes", zh: "手套", example: { es: "Guantes de invierno.", zh: "冬季手套。" } },
      { es: "gafas", zh: "眼镜", example: { es: "Gafas de sol.", zh: "太阳镜。" } },
      { es: "anteojos", zh: "眼镜（拉美）", example: { es: "Anteojos nuevos.", zh: "新眼镜。" } },
      { es: "reloj", zh: "手表", example: { es: "Reloj de pulsera.", zh: "腕表。" } },
      { es: "collar", zh: "项链", example: { es: "Collar de oro.", zh: "金项链。" } },
      { es: "pulsera", zh: "手链", example: { es: "Pulsera de plata.", zh: "银手链。" } },
      { es: "anillo", zh: "戒指", example: { es: "Anillo de boda.", zh: "婚戒。" } },
      { es: "pendiente", zh: "耳环", example: { es: "Pendientes de perlas.", zh: "珍珠耳环。" } },
      { es: "arete", zh: "耳环（拉美）", example: { es: "Aretes brillantes.", zh: "闪亮的耳环。" } }
    ]
  },

  // ============ Unit 12: 家居物品 ============
  {
    id: 12, title: "家居物品", emoji: "🏠", color: "from-amber-400 to-amber-600", iconColor: "#FFC800",
    tip: "家具和房间词很多以 -a 结尾。Mi casa 我的家，en casa 在家。",
    words: [
      { es: "casa", zh: "房子/家", example: { es: "Mi casa.", zh: "我的家。" } },
      { es: "hogar", zh: "家（温馨）", example: { es: "Hogar dulce hogar.", zh: "家，甜蜜的家。" } },
      { es: "habitación", zh: "房间", example: { es: "Mi habitación.", zh: "我的房间。" } },
      { es: "cuarto", zh: "房间", example: { es: "El cuarto de baño.", zh: "浴室。" } },
      { es: "dormitorio", zh: "卧室", example: { es: "Dormitorio grande.", zh: "大卧室。" } },
      { es: "sala", zh: "客厅", example: { es: "Sala de estar.", zh: "客厅。" } },
      { es: "comedor", zh: "餐厅", example: { es: "El comedor.", zh: "餐厅。" } },
      { es: "cocina", zh: "厨房", example: { es: "Cocina moderna.", zh: "现代厨房。" } },
      { es: "baño", zh: "浴室", example: { es: "El baño.", zh: "浴室。" } },
      { es: "balcón", zh: "阳台", example: { es: "Balcón con vista.", zh: "有风景的阳台。" } },
      { es: "jardín", zh: "花园", example: { es: "Jardín bonito.", zh: "漂亮的花园。" } },
      { es: "garaje", zh: "车库", example: { es: "El garaje.", zh: "车库。" } },
      { es: "sótano", zh: "地下室", example: { es: "El sótano.", zh: "地下室。" } },
      { es: "ático", zh: "阁楼", example: { es: "Ático luminoso.", zh: "明亮的阁楼。" } },
      { es: "puerta", zh: "门", example: { es: "La puerta.", zh: "门。" } },
      { es: "ventana", zh: "窗", example: { es: "Ventana grande.", zh: "大窗户。" } },
      { es: "techo", zh: "天花板", example: { es: "Techo alto.", zh: "高天花板。" } },
      { es: "suelo", zh: "地板", example: { es: "Suelo de madera.", zh: "木地板。" } },
      { es: "pared", zh: "墙", example: { es: "Pared blanca.", zh: "白墙。" } },
      { es: "escalera", zh: "楼梯", example: { es: "Escalera de caracol.", zh: "螺旋楼梯。" } },
      { es: "ascensor", zh: "电梯", example: { es: "El ascensor.", zh: "电梯。" } },
      { es: "mesa", zh: "桌子", example: { es: "Mesa de madera.", zh: "木桌。" } },
      { es: "silla", zh: "椅子", example: { es: "Una silla.", zh: "一把椅子。" } },
      { es: "sillón", zh: "扶手椅", example: { es: "Sillón cómodo.", zh: "舒适的扶手椅。" } },
      { es: "sofá", zh: "沙发", example: { es: "Sofá grande.", zh: "大沙发。" } },
      { es: "cama", zh: "床", example: { es: "Mi cama.", zh: "我的床。" } },
      { es: "almohada", zh: "枕头", example: { es: "Almohada blanda.", zh: "软枕头。" } },
      { es: "sábana", zh: "床单", example: { es: "Sábanas blancas.", zh: "白床单。" } },
      { es: "manta", zh: "毯子", example: { es: "Manta caliente.", zh: "暖毯子。" } },
      { es: "armario", zh: "衣柜", example: { es: "Armario grande.", zh: "大衣柜。" } },
      { es: "cajón", zh: "抽屉", example: { es: "Un cajón.", zh: "一个抽屉。" } },
      { es: "estante", zh: "架子", example: { es: "Estante de libros.", zh: "书架。" } },
      { es: "lámpara", zh: "灯", example: { es: "Lámpara de mesa.", zh: "台灯。" } },
      { es: "lámpara", zh: "灯", example: { es: "Lámpara brillante.", zh: "明亮的灯。" } },
      { es: "espejo", zh: "镜子", example: { es: "Espejo grande.", zh: "大镜子。" } },
      { es: "cuadro", zh: "画框/画", example: { es: "Cuadro bonito.", zh: "漂亮的画。" } },
      { es: "reloj", zh: "钟", example: { es: "Reloj de pared.", zh: "挂钟。" } },
      { es: "alfombra", zh: "地毯", example: { es: "Alfombra suave.", zh: "柔软的地毯。" } },
      { es: "cortina", zh: "窗帘", example: { es: "Cortinas azules.", zh: "蓝窗帘。" } },
      { es: "nevera", zh: "冰箱", example: { es: "La nevera.", zh: "冰箱。" } },
      { es: "refrigerador", zh: "冰箱（拉美）", example: { es: "Refrigerador nuevo.", zh: "新冰箱。" } },
      { es: "horno", zh: "烤箱", example: { es: "Horno caliente.", zh: "热烤箱。" } },
      { es: "estufa", zh: "炉子", example: { es: "La estufa.", zh: "炉子。" } },
      { es: "microondas", zh: "微波炉", example: { es: "Microondas nuevo.", zh: "新微波炉。" } },
      { es: "lavadora", zh: "洗衣机", example: { es: "Lavadora rota.", zh: "坏了的洗衣机。" } },
      { es: "televisión", zh: "电视", example: { es: "Televisión grande.", zh: "大电视。" } },
      { es: "tele", zh: "电视（口语）", example: { es: "Ver la tele.", zh: "看电视。" } },
      { es: "computadora", zh: "电脑", example: { es: "Computadora portátil.", zh: "笔记本电脑。" } },
      { es: "ordenador", zh: "电脑（西）", example: { es: "Ordenador nuevo.", zh: "新电脑。" } },
      { es: "teléfono", zh: "电话", example: { es: "Mi teléfono.", zh: "我的电话。" } },
      { es: "llave", zh: "钥匙", example: { es: "Las llaves.", zh: "钥匙。" } },
      { es: "candado", zh: "锁", example: { es: "Candado seguro.", zh: "安全的锁。" } }
    ]
  },

  // ============ Unit 13: 城市地点 ============
  {
    id: 13, title: "城市地点", emoji: "🏙️", color: "from-slate-400 to-slate-600", iconColor: "#1CB0F6",
    tip: "公共场所常以 el/la + 名词。问路用 ¿Dónde está...?(在哪里)",
    words: [
      { es: "ciudad", zh: "城市", example: { es: "La ciudad.", zh: "城市。" } },
      { es: "pueblo", zh: "小镇", example: { es: "Pueblo pequeño.", zh: "小镇。" } },
      { es: "calle", zh: "街道", example: { es: "Calle principal.", zh: "主街。" } },
      { es: "avenida", zh: "大街", example: { es: "Avenida ancha.", zh: "宽大街。" } },
      { es: "plaza", zh: "广场", example: { es: "Plaza central.", zh: "中心广场。" } },
      { es: "parque", zh: "公园", example: { es: "Parque bonito.", zh: "漂亮的公园。" } },
      { es: "banco", zh: "银行", example: { es: "El banco.", zh: "银行。" } },
      { es: "hospital", zh: "医院", example: { es: "Hospital grande.", zh: "大医院。" } },
      { es: "farmacia", zh: "药店", example: { es: "La farmacia.", zh: "药店。" } },
      { es: "escuela", zh: "学校", example: { es: "La escuela.", zh: "学校。" } },
      { es: "colegio", zh: "中小学", example: { es: "El colegio.", zh: "中小学。" } },
      { es: "universidad", zh: "大学", example: { es: "La universidad.", zh: "大学。" } },
      { es: "biblioteca", zh: "图书馆", example: { es: "La biblioteca.", zh: "图书馆。" } },
      { es: "iglesia", zh: "教堂", example: { es: "Iglesia antigua.", zh: "古老的教堂。" } },
      { es: "tienda", zh: "商店", example: { es: "La tienda.", zh: "商店。" } },
      { es: "supermercado", zh: "超市", example: { es: "Supermercado grande.", zh: "大超市。" } },
      { es: "mercado", zh: "市场", example: { es: "Mercado al aire libre.", zh: "露天市场。" } },
      { es: "panadería", zh: "面包店", example: { es: "La panadería.", zh: "面包店。" } },
      { es: "carnicería", zh: "肉店", example: { es: "La carnicería.", zh: "肉店。" } },
      { es: "pescadería", zh: "鱼店", example: { es: "La pescadería.", zh: "鱼店。" } },
      { es: "frutería", zh: "水果店", example: { es: "La frutería.", zh: "水果店。" } },
      { es: "peluquería", zh: "理发店", example: { es: "La peluquería.", zh: "理发店。" } },
      { es: "restaurante", zh: "餐厅", example: { es: "Restaurante italiano.", zh: "意大利餐厅。" } },
      { es: "cafetería", zh: "咖啡馆", example: { es: "La cafetería.", zh: "咖啡馆。" } },
      { es: "hotel", zh: "酒店", example: { es: "Hotel de cinco estrellas.", zh: "五星酒店。" } },
      { es: "cine", zh: "电影院", example: { es: "Ir al cine.", zh: "去电影院。" } },
      { es: "teatro", zh: "剧院", example: { es: "El teatro.", zh: "剧院。" } },
      { es: "museo", zh: "博物馆", example: { es: "Museo del Prado.", zh: "普拉多博物馆。" } },
      { es: "gimnasio", zh: "健身房", example: { es: "El gimnasio.", zh: "健身房。" } },
      { es: "piscina", zh: "游泳池", example: { es: "Piscina pública.", zh: "公共游泳池。" } },
      { es: "oficina", zh: "办公室", example: { es: "La oficina.", zh: "办公室。" } },
      { es: "estación", zh: "车站", example: { es: "Estación de tren.", zh: "火车站。" } },
      { es: "aeropuerto", zh: "机场", example: { es: "El aeropuerto.", zh: "机场。" } },
      { es: "puerto", zh: "港口", example: { es: "Puerto marítimo.", zh: "海港。" } },
      { es: "estadio", zh: "体育场", example: { es: "Estadio grande.", zh: "大体育场。" } },
      { es: "mapa", zh: "地图", example: { es: "El mapa.", zh: "地图。" } },
      { es: "dirección", zh: "地址", example: { es: "Mi dirección.", zh: "我的地址。" } },
      { es: "semáforo", zh: "红绿灯", example: { es: "El semáforo.", zh: "红绿灯。" } },
      { es: "puente", zh: "桥", example: { es: "Puente viejo.", zh: "老桥。" } },
      { es: "edificio", zh: "建筑", example: { es: "Edificio alto.", zh: "高楼。" } },
      { es: "casa", zh: "房子", example: { es: "Casa blanca.", zh: "白房子。" } },
      { es: "piso", zh: "公寓/楼层", example: { es: "Tercer piso.", zh: "三楼。" } }
    ]
  },

  // ============ Unit 14: 交通出行 ============
  {
    id: 14, title: "交通出行", emoji: "🚗", color: "from-blue-500 to-indigo-600", iconColor: "#1CB0F6",
    tip: "动词 ir (去)。交通工具前用 en (坐)。Quiero ir a... 我想去...",
    words: [
      { es: "coche", zh: "汽车", example: { es: "Mi coche.", zh: "我的车。" } },
      { es: "carro", zh: "汽车（拉美）", example: { es: "El carro.", zh: "汽车。" } },
      { es: "auto", zh: "汽车（西）", example: { es: "Auto nuevo.", zh: "新车。" } },
      { es: "autobús", zh: "公交车", example: { es: "El autobús.", zh: "公交车。" } },
      { es: "camión", zh: "卡车", example: { es: "Camión grande.", zh: "大卡车。" } },
      { es: "tren", zh: "火车", example: { es: "Tren rápido.", zh: "快速火车。" } },
      { es: "metro", zh: "地铁", example: { es: "En metro.", zh: "坐地铁。" } },
      { es: "subte", zh: "地铁（阿根廷）", example: { es: "El subte.", zh: "地铁。" } },
      { es: "taxi", zh: "出租车", example: { es: "Un taxi.", zh: "一辆出租车。" } },
      { es: "avión", zh: "飞机", example: { es: "Avión grande.", zh: "大飞机。" } },
      { es: "barco", zh: "船", example: { es: "El barco.", zh: "船。" } },
      { es: "barco", zh: "船", example: { es: "Barco velero.", zh: "帆船。" } },
      { es: "bicicleta", zh: "自行车", example: { es: "Mi bicicleta.", zh: "我的自行车。" } },
      { es: "bici", zh: "自行车（口语）", example: { es: "En bici.", zh: "骑自行车。" } },
      { es: "motocicleta", zh: "摩托车", example: { es: "Motocicleta rápida.", zh: "快摩托车。" } },
      { es: "moto", zh: "摩托车（口语）", example: { es: "Una moto.", zh: "一辆摩托。" } },
      { es: "tren", zh: "火车", example: { es: "Tren de alta velocidad.", zh: "高铁。" } },
      { es: "helicóptero", zh: "直升机", example: { es: "Helicóptero militar.", zh: "军用直升机。" } },
      { es: "viaje", zh: "旅行", example: { es: "Buen viaje.", zh: "旅途愉快。" } },
      { es: "boleto", zh: "票", example: { es: "Boleto de avión.", zh: "机票。" } },
      { es: "billete", zh: "票（西）", example: { es: "Billete de tren.", zh: "火车票。" } },
      { es: "pasaporte", zh: "护照", example: { es: "Mi pasaporte.", zh: "我的护照。" } },
      { es: "maleta", zh: "行李箱", example: { es: "Maleta grande.", zh: "大行李箱。" } },
      { es: "equipaje", zh: "行李", example: { es: "Mi equipaje.", zh: "我的行李。" } },
      { es: "aerolínea", zh: "航空公司", example: { es: "Aerolínea española.", zh: "西班牙航空公司。" } },
      { es: "vuelo", zh: "航班", example: { es: "Vuelo a Madrid.", zh: "去马德里的航班。" } },
      { es: "piloto", zh: "飞行员", example: { es: "El piloto.", zh: "飞行员。" } },
      { es: "conductor", zh: "司机", example: { es: "El conductor.", zh: "司机。" } },
      { es: "pasajero", zh: "乘客", example: { es: "Pasajeros.", zh: "乘客们。" } },
      { es: "estación", zh: "车站", example: { es: "Estación de tren.", zh: "火车站。" } },
      { es: "parada", zh: "停靠站", example: { es: "Parada de bus.", zh: "公交站。" } },
      { es: "andén", zh: "站台", example: { es: "El andén.", zh: "站台。" } },
      { es: "calle", zh: "街", example: { es: "Cruzar la calle.", zh: "过马路。" } },
      { es: "carretera", zh: "公路", example: { es: "Carretera larga.", zh: "长公路。" } },
      { es: "autopista", zh: "高速公路", example: { es: "La autopista.", zh: "高速。" } },
      { es: "puente", zh: "桥", example: { es: "Puente sobre el río.", zh: "河上的桥。" } },
      { es: "túnel", zh: "隧道", example: { es: "El túnel.", zh: "隧道。" } },
      { es: "gasolina", zh: "汽油", example: { es: "Gasolina cara.", zh: "贵的油。" } },
      { es: "gasolinera", zh: "加油站", example: { es: "La gasolinera.", zh: "加油站。" } },
      { es: "semáforo", zh: "红绿灯", example: { es: "El semáforo en rojo.", zh: "红灯。" } },
      { es: "izquierda", zh: "左", example: { es: "A la izquierda.", zh: "向左。" } },
      { es: "derecha", zh: "右", example: { es: "A la derecha.", zh: "向右。" } },
      { es: "recto", zh: "直走", example: { es: "Sigue recto.", zh: "直走。" } },
      { es: "cerca", zh: "近", example: { es: "Está cerca.", zh: "很近。" } },
      { es: "lejos", zh: "远", example: { es: "Está lejos.", zh: "很远。" } }
    ]
  },

  // ============ Unit 15: 学校学习 ============
  {
    id: 15, title: "学校学习", emoji: "📚", color: "from-violet-400 to-violet-600", iconColor: "#CE82FF",
    tip: "学习用品词很多以 -o 结尾。学科名常用 las + 阴性名词。",
    words: [
      { es: "escuela", zh: "学校", example: { es: "La escuela.", zh: "学校。" } },
      { es: "colegio", zh: "中小学", example: { es: "El colegio.", zh: "中小学。" } },
      { es: "clase", zh: "课/班级", example: { es: "La clase.", zh: "课。" } },
      { es: "aula", zh: "教室", example: { es: "El aula.", zh: "教室。" } },
      { es: "profesor", zh: "老师（男）", example: { es: "Mi profesor.", zh: "我的老师。" } },
      { es: "profesora", zh: "老师（女）", example: { es: "Mi profesora.", zh: "我的老师。" } },
      { es: "maestro", zh: "小学老师（男）", example: { es: "El maestro.", zh: "老师。" } },
      { es: "maestra", zh: "小学老师（女）", example: { es: "La maestra.", zh: "老师。" } },
      { es: "alumno", zh: "学生（男）", example: { es: "Un alumno.", zh: "一个学生。" } },
      { es: "alumna", zh: "学生（女）", example: { es: "Una alumna.", zh: "一个学生。" } },
      { es: "estudiante", zh: "学生（中性）", example: { es: "Estudiante aplicado.", zh: "用功的学生。" } },
      { es: "compañero", zh: "同学（男）", example: { es: "Mi compañero.", zh: "我同学。" } },
      { es: "compañera", zh: "同学（女）", example: { es: "Mi compañera.", zh: "我同学。" } },
      { es: "amigo", zh: "朋友", example: { es: "Mi amigo.", zh: "我朋友。" } },
      { es: "director", zh: "校长（男）", example: { es: "El director.", zh: "校长。" } },
      { es: "directora", zh: "校长（女）", example: { es: "La directora.", zh: "校长。" } },
      { es: "libro", zh: "书", example: { es: "Un libro.", zh: "一本书。" } },
      { es: "cuaderno", zh: "笔记本", example: { es: "Mi cuaderno.", zh: "我的笔记本。" } },
      { es: "libreta", zh: "本子", example: { es: "Libreta pequeña.", zh: "小本子。" } },
      { es: "lápiz", zh: "铅笔", example: { es: "Un lápiz.", zh: "一支铅笔。" } },
      { es: "bolígrafo", zh: "圆珠笔", example: { es: "Bolígrafo azul.", zh: "蓝圆珠笔。" } },
      { es: "pluma", zh: "钢笔", example: { es: "Pluma de oro.", zh: "金笔。" } },
      { es: "goma", zh: "橡皮", example: { es: "La goma.", zh: "橡皮。" } },
      { es: "sacapuntas", zh: "卷笔刀", example: { es: "El sacapuntas.", zh: "卷笔刀。" } },
      { es: "mochila", zh: "书包", example: { es: "La mochila.", zh: "书包。" } },
      { es: "regla", zh: "尺子", example: { es: "La regla.", zh: "尺子。" } },
      { es: "tijeras", zh: "剪刀", example: { es: "Las tijeras.", zh: "剪刀。" } },
      { es: "pegamento", zh: "胶水", example: { es: "El pegamento.", zh: "胶水。" } },
      { es: "papel", zh: "纸", example: { es: "Papel blanco.", zh: "白纸。" } },
      { es: "hoja", zh: "页/叶子", example: { es: "Una hoja de papel.", zh: "一张纸。" } },
      { es: "pizarra", zh: "黑板", example: { es: "La pizarra.", zh: "黑板。" } },
      { es: "pizarra", zh: "黑板", example: { es: "Pizarra verde.", zh: "绿黑板。" } },
      { es: "tiza", zh: "粉笔", example: { es: "Tiza blanca.", zh: "白粉笔。" } },
      { es: "marcador", zh: "马克笔", example: { es: "Marcador rojo.", zh: "红马克笔。" } },
      { es: "borrador", zh: "黑板擦", example: { es: "El borrador.", zh: "黑板擦。" } },
      { es: "escritorio", zh: "书桌", example: { es: "Escritorio grande.", zh: "大书桌。" } },
      { es: "silla", zh: "椅子", example: { es: "Silla escolar.", zh: "学校椅子。" } },
      { es: "examen", zh: "考试", example: { es: "Examen difícil.", zh: "难考试。" } },
      { es: "prueba", zh: "测试", example: { es: "Una prueba.", zh: "一次测试。" } },
      { es: "tarea", zh: "作业", example: { es: "La tarea.", zh: "作业。" } },
      { es: "deberes", zh: "作业（复）", example: { es: "Mis deberes.", zh: "我的作业。" } },
      { es: "lección", zh: "课程/课", example: { es: "Lección diez.", zh: "第十课。" } },
      { es: "matemáticas", zh: "数学", example: { es: "Clase de matemáticas.", zh: "数学课。" } },
      { es: "español", zh: "西语", example: { es: "Clase de español.", zh: "西语课。" } },
      { es: "inglés", zh: "英语", example: { es: "Aprendo inglés.", zh: "我学英语。" } },
      { es: "ciencias", zh: "科学", example: { es: "Ciencias naturales.", zh: "自然科学。" } },
      { es: "historia", zh: "历史", example: { es: "La historia.", zh: "历史。" } },
      { es: "geografía", zh: "地理", example: { es: "Geografía mundial.", zh: "世界地理。" } },
      { es: "arte", zh: "艺术", example: { es: "Clase de arte.", zh: "美术课。" } },
      { es: "música", zh: "音乐", example: { es: "La música.", zh: "音乐。" } },
      { es: "educación física", zh: "体育", example: { es: "Educación física.", zh: "体育课。" } },
      { es: "informática", zh: "信息技术", example: { es: "Clase de informática.", zh: "信息技术课。" } }
    ]
  },

  // ============ Unit 16: 工作职业 ============
  {
    id: 16, title: "工作职业", emoji: "👨‍⚕️", color: "from-teal-400 to-teal-600", iconColor: "#58CC02",
    tip: "职业名词男女成对：médico/médica。Soy + 职业 = 我是...。",
    words: [
      { es: "trabajo", zh: "工作", example: { es: "Mi trabajo.", zh: "我的工作。" } },
      { es: "empleo", zh: "就业", example: { es: "Buen empleo.", zh: "好工作。" } },
      { es: "oficio", zh: "手艺", example: { es: "Oficio artesanal.", zh: "手艺活。" } },
      { es: "profesión", zh: "职业", example: { es: "¿Su profesión?", zh: "您的职业？" } },
      { es: "jefe", zh: "老板（男）", example: { es: "Mi jefe.", zh: "我老板。" } },
      { es: "jefa", zh: "老板（女）", example: { es: "Mi jefa.", zh: "我老板。" } },
      { es: "doctor", zh: "医生（男）", example: { es: "El doctor.", zh: "医生。" } },
      { es: "doctora", zh: "医生（女）", example: { es: "La doctora.", zh: "医生。" } },
      { es: "médico", zh: "医生", example: { es: "Médico amable.", zh: "和蔼的医生。" } },
      { es: "enfermero", zh: "护士（男）", example: { es: "El enfermero.", zh: "护士。" } },
      { es: "enfermera", zh: "护士（女）", example: { es: "La enfermera.", zh: "护士。" } },
      { es: "profesor", zh: "教授/老师", example: { es: "Profesor universitario.", zh: "大学教授。" } },
      { es: "abogado", zh: "律师（男）", example: { es: "El abogado.", zh: "律师。" } },
      { es: "abogada", zh: "律师（女）", example: { es: "La abogada.", zh: "律师。" } },
      { es: "ingeniero", zh: "工程师（男）", example: { es: "El ingeniero.", zh: "工程师。" } },
      { es: "ingeniera", zh: "工程师（女）", example: { es: "La ingeniera.", zh: "工程师。" } },
      { es: "arquitecto", zh: "建筑师（男）", example: { es: "El arquitecto.", zh: "建筑师。" } },
      { es: "cocinero", zh: "厨师（男）", example: { es: "El cocinero.", zh: "厨师。" } },
      { es: "cocinera", zh: "厨师（女）", example: { es: "La cocinera.", zh: "厨师。" } },
      { es: "camarero", zh: "服务员（男）", example: { es: "El camarero.", zh: "服务员。" } },
      { es: "camarera", zh: "服务员（女）", example: { es: "La camarera.", zh: "服务员。" } },
      { es: "mesero", zh: "服务员（拉美）", example: { es: "El mesero.", zh: "服务员。" } },
      { es: "bombero", zh: "消防员", example: { es: "El bombero.", zh: "消防员。" } },
      { es: "policía", zh: "警察", example: { es: "El policía.", zh: "警察。" } },
      { es: "militar", zh: "军人", example: { es: "Militar valiente.", zh: "勇敢的军人。" } },
      { es: "cartero", zh: "邮递员", example: { es: "El cartero.", zh: "邮递员。" } },
      { es: "panadero", zh: "面包师", example: { es: "El panadero.", zh: "面包师。" } },
      { es: "dentista", zh: "牙医", example: { es: "El dentista.", zh: "牙医。" } },
      { es: "veterinario", zh: "兽医", example: { es: "El veterinario.", zh: "兽医。" } },
      { es: "periodista", zh: "记者", example: { es: "Periodista famosa.", zh: "著名记者。" } },
      { es: "escritor", zh: "作家（男）", example: { es: "El escritor.", zh: "作家。" } },
      { es: "escritora", zh: "作家（女）", example: { es: "La escritora.", zh: "作家。" } },
      { es: "pintor", zh: "画家（男）", example: { es: "El pintor.", zh: "画家。" } },
      { es: "músico", zh: "音乐家", example: { es: "Músico talentoso.", zh: "天才音乐家。" } },
      { es: "actor", zh: "演员（男）", example: { es: "El actor.", zh: "演员。" } },
      { es: "actriz", zh: "演员（女）", example: { es: "La actriz.", zh: "女演员。" } },
      { es: "cantante", zh: "歌手", example: { es: "Cantante famosa.", zh: "著名歌手。" } },
      { es: "bailarín", zh: "舞者（男）", example: { es: "El bailarín.", zh: "舞者。" } },
      { es: "bailarina", zh: "舞者（女）", example: { es: "La bailarina.", zh: "舞者。" } },
      { es: "deportista", zh: "运动员", example: { es: "Deportista famoso.", zh: "著名运动员。" } },
      { es: "granjero", zh: "农民", example: { es: "El granjero.", zh: "农民。" } },
      { es: "jardinero", zh: "园丁", example: { es: "El jardinero.", zh: "园丁。" } },
      { es: "peluquero", zh: "理发师（男）", example: { es: "El peluquero.", zh: "理发师。" } },
      { es: "dependiente", zh: "店员", example: { es: "El dependiente.", zh: "店员。" } },
      { es: "sueldo", zh: "工资", example: { es: "Buen sueldo.", zh: "好工资。" } },
      { es: "salario", zh: "薪水", example: { es: "Salario justo.", zh: "公平薪水。" } },
      { es: "empresa", zh: "公司", example: { es: "La empresa.", zh: "公司。" } },
      { es: "oficina", zh: "办公室", example: { es: "Oficina moderna.", zh: "现代办公室。" } }
    ]
  },

  // ============ Unit 17: 体育运动 ============
  {
    id: 17, title: "体育运动", emoji: "⚽", color: "from-emerald-400 to-emerald-600", iconColor: "#58CC02",
    tip: "动词 jugar (玩/打) + a + 运动。Practicar (练习) + 运动。",
    words: [
      { es: "deporte", zh: "运动", example: { es: "Deporte favorito.", zh: "最喜欢的运动。" } },
      { es: "fútbol", zh: "足球", example: { es: "Fútbol es popular.", zh: "足球很流行。" } },
      { es: "baloncesto", zh: "篮球", example: { es: "Baloncesto rápido.", zh: "快篮球。" } },
      { es: "tenis", zh: "网球", example: { es: "Tenis profesional.", zh: "职业网球。" } },
      { es: "natación", zh: "游泳", example: { es: "Natación en piscina.", zh: "在泳池游泳。" } },
      { es: "correr", zh: "跑步", example: { es: "Me gusta correr.", zh: "我喜欢跑步。" } },
      { es: "ciclismo", zh: "自行车运动", example: { es: "Ciclismo profesional.", zh: "职业自行车。" } },
      { es: "golf", zh: "高尔夫", example: { es: "Jugar al golf.", zh: "打高尔夫。" } },
      { es: "béisbol", zh: "棒球", example: { es: "Béisbol americano.", zh: "美式棒球。" } },
      { es: "vóleibol", zh: "排球", example: { es: "Vóleibol de playa.", zh: "沙滩排球。" } },
      { es: "rugby", zh: "橄榄球", example: { es: "Rugby duro.", zh: "硬橄榄球。" } },
      { es: "boxeo", zh: "拳击", example: { es: "Boxeo fuerte.", zh: "强拳击。" } },
      { es: "karate", zh: "空手道", example: { es: "Karate japonés.", zh: "日式空手道。" } },
      { es: "yoga", zh: "瑜伽", example: { es: "Yoga relajante.", zh: "放松瑜伽。" } },
      { es: "gimnasia", zh: "体操", example: { es: "Gimnasia artística.", zh: "艺术体操。" } },
      { es: "esquí", zh: "滑雪", example: { es: "Esquí en la nieve.", zh: "在雪中滑雪。" } },
      { es: "surf", zh: "冲浪", example: { es: "Surf en el mar.", zh: "海上冲浪。" } },
      { es: "buceo", zh: "潜水", example: { es: "Buceo profundo.", zh: "深潜。" } },
      { es: "escalada", zh: "攀岩", example: { es: "Escalada en roca.", zh: "攀岩。" } },
      { es: "senderismo", zh: "徒步", example: { es: "Senderismo en la montaña.", zh: "山中徒步。" } },
      { es: "atletismo", zh: "田径", example: { es: "Atletismo olímpico.", zh: "奥林匹克田径。" } },
      { es: "gimnasio", zh: "健身房", example: { es: "Voy al gimnasio.", zh: "我去健身房。" } },
      { es: "equipo", zh: "团队/队", example: { es: "Nuestro equipo.", zh: "我们的队。" } },
      { es: "partido", zh: "比赛", example: { es: "El partido.", zh: "比赛。" } },
      { es: "juego", zh: "游戏/比赛", example: { es: "Un juego.", zh: "一场游戏。" } },
      { es: "victoria", zh: "胜利", example: { es: "¡Victoria!", zh: "胜利！" } },
      { es: "derrota", zh: "失败", example: { es: "Dura derrota.", zh: "惨败。" } },
      { es: "ganar", zh: "赢", example: { es: "Vamos a ganar.", zh: "我们要赢。" } },
      { es: "perder", zh: "输", example: { es: "No quiero perder.", zh: "我不想输。" } },
      { es: "jugador", zh: "球员（男）", example: { es: "El jugador.", zh: "球员。" } },
      { es: "jugadora", zh: "球员（女）", example: { es: "La jugadora.", zh: "球员。" } },
      { es: "entrenador", zh: "教练（男）", example: { es: "El entrenador.", zh: "教练。" } },
      { es: "entrenadora", zh: "教练（女）", example: { es: "La entrenadora.", zh: "教练。" } },
      { es: "árbitro", zh: "裁判", example: { es: "El árbitro.", zh: "裁判。" } },
      { es: "estadio", zh: "体育场", example: { es: "Estadio lleno.", zh: "满座的体育场。" } },
      { es: "cancha", zh: "球场", example: { es: "La cancha.", zh: "球场。" } },
      { es: "campo", zh: "场地", example: { es: "Campo de fútbol.", zh: "足球场。" } },
      { es: "pelota", zh: "球", example: { es: "La pelota.", zh: "球。" } },
      { es: "balón", zh: "球（足球用）", example: { es: "El balón.", zh: "球。" } },
      { es: "raqueta", zh: "球拍", example: { es: "La raqueta.", zh: "球拍。" } },
      { es: "trofeo", zh: "奖杯", example: { es: "Trofeo de oro.", zh: "金奖杯。" } },
      { es: "medalla", zh: "奖牌", example: { es: "Medalla de oro.", zh: "金牌。" } },
      { es: "campeonato", zh: "锦标赛", example: { es: "Campeonato mundial.", zh: "世界锦标赛。" } },
      { es: "mundial", zh: "世界杯", example: { es: "Mundial 2026.", zh: "2026 世界杯。" } }
    ]
  },

  // ============ Unit 18: 娱乐爱好 ============
  {
    id: 18, title: "娱乐爱好", emoji: "🎮", color: "from-fuchsia-400 to-fuchsia-600", iconColor: "#CE82FF",
    tip: "Me gusta + 名词/动词原形 = 我喜欢。动词原形以 -ar, -er, -ir 结尾。",
    words: [
      { es: "hobby", zh: "爱好", example: { es: "Mi hobby favorito.", zh: "我最喜欢的爱好。" } },
      { es: "afición", zh: "爱好", example: { es: "Mi afición.", zh: "我的爱好。" } },
      { es: "música", zh: "音乐", example: { es: "Me gusta la música.", zh: "我喜欢音乐。" } },
      { es: "película", zh: "电影", example: { es: "Una película buena.", zh: "一部好电影。" } },
      { es: "canción", zh: "歌曲", example: { es: "Canción bonita.", zh: "好听的歌。" } },
      { es: "juego", zh: "游戏", example: { es: "Juego divertido.", zh: "有趣的游戏。" } },
      { es: "videojuego", zh: "电子游戏", example: { es: "Videojuego popular.", zh: "流行游戏。" } },
      { es: "lectura", zh: "阅读", example: { es: "Me gusta la lectura.", zh: "我喜欢阅读。" } },
      { es: "libro", zh: "书", example: { es: "Un libro interesante.", zh: "一本有趣的书。" } },
      { es: "novela", zh: "小说", example: { es: "Novela policíaca.", zh: "侦探小说。" } },
      { es: "cuento", zh: "故事", example: { es: "Cuento corto.", zh: "短故事。" } },
      { es: "revista", zh: "杂志", example: { es: "Revista de moda.", zh: "时尚杂志。" } },
      { es: "periódico", zh: "报纸", example: { es: "El periódico.", zh: "报纸。" } },
      { es: "televisión", zh: "电视", example: { es: "Ver televisión.", zh: "看电视。" } },
      { es: "programa", zh: "节目", example: { es: "Programa de TV.", zh: "电视节目。" } },
      { es: "serie", zh: "连续剧", example: { es: "Serie dramática.", zh: "剧情剧。" } },
      { es: "dibujo", zh: "绘画", example: { es: "Dibujo artístico.", zh: "艺术画。" } },
      { es: "pintura", zh: "绘画（作品）", example: { es: "Pintura famosa.", zh: "名画。" } },
      { es: "fotografía", zh: "摄影", example: { es: "Fotografía digital.", zh: "数码摄影。" } },
      { es: "cocina", zh: "烹饪", example: { es: "Me gusta la cocina.", zh: "我喜欢烹饪。" } },
      { es: "bailar", zh: "跳舞", example: { es: "Me gusta bailar.", zh: "我喜欢跳舞。" } },
      { es: "cantar", zh: "唱歌", example: { es: "Me gusta cantar.", zh: "我喜欢唱歌。" } },
      { es: "tocar", zh: "弹/演奏", example: { es: "Tocar la guitarra.", zh: "弹吉他。" } },
      { es: "guitarra", zh: "吉他", example: { es: "Guitarra eléctrica.", zh: "电吉他。" } },
      { es: "piano", zh: "钢琴", example: { es: "Tocar el piano.", zh: "弹钢琴。" } },
      { es: "violín", zh: "小提琴", example: { es: "El violín.", zh: "小提琴。" } },
      { es: "batería", zh: "鼓", example: { es: "Tocar la batería.", zh: "打鼓。" } },
      { es: "flauta", zh: "笛子", example: { es: "La flauta.", zh: "笛子。" } },
      { es: "instrumento", zh: "乐器", example: { es: "Instrumento musical.", zh: "乐器。" } },
      { es: "instrumento", zh: "乐器", example: { es: "Un instrumento.", zh: "一种乐器。" } },
      { es: "baile", zh: "舞蹈", example: { es: "Clase de baile.", zh: "舞蹈课。" } },
      { es: "danza", zh: "舞蹈", example: { es: "Danza clásica.", zh: "古典舞。" } },
      { es: "teatro", zh: "戏剧", example: { es: "Obra de teatro.", zh: "戏剧作品。" } },
      { es: "concierto", zh: "音乐会", example: { es: "Concierto en vivo.", zh: "现场音乐会。" } },
      { es: "fiesta", zh: "派对", example: { es: "Fiesta divertida.", zh: "有趣的派对。" } },
      { es: "parque", zh: "公园", example: { es: "Ir al parque.", zh: "去公园。" } },
      { es: "playa", zh: "海滩", example: { es: "Playa bonita.", zh: "漂亮的海滩。" } },
      { es: "montaña", zh: "山", example: { es: "Montaña alta.", zh: "高山。" } },
      { es: "bosque", zh: "森林", example: { es: "Bosque verde.", zh: "绿森林。" } },
      { es: "viaje", zh: "旅行", example: { es: "Viaje al extranjero.", zh: "出国旅行。" } },
      { es: "vacaciones", zh: "假期", example: { es: "Vacaciones de verano.", zh: "暑假。" } },
      { es: "fiesta", zh: "节日", example: { es: "Fiesta nacional.", zh: "国庆节。" } },
      { es: "celebración", zh: "庆典", example: { es: "Gran celebración.", zh: "盛大庆典。" } }
    ]
  },

  // ============ Unit 19: 形容词 ============
  {
    id: 19, title: "形容词", emoji: "✨", color: "from-pink-500 to-purple-600", iconColor: "#CE82FF",
    tip: "形容词放名词后，要和名词性数配合：niño alto (单)，niños altos (复)。",
    words: [
      { es: "bueno", zh: "好的", example: { es: "Buen chico.", zh: "好孩子。" } },
      { es: "malo", zh: "坏的", example: { es: "Mal tiempo.", zh: "坏天气。" } },
      { es: "grande", zh: "大", example: { es: "Casa grande.", zh: "大房子。" } },
      { es: "pequeño", zh: "小", example: { es: "Perro pequeño.", zh: "小狗。" } },
      { es: "alto", zh: "高", example: { es: "Edificio alto.", zh: "高楼。" } },
      { es: "bajo", zh: "矮/低", example: { es: "Mesa baja.", zh: "矮桌。" } },
      { es: "largo", zh: "长", example: { es: "Pelo largo.", zh: "长发。" } },
      { es: "corto", zh: "短", example: { es: "Pelo corto.", zh: "短发。" } },
      { es: "nuevo", zh: "新的", example: { es: "Coche nuevo.", zh: "新车。" } },
      { es: "viejo", zh: "旧的/老", example: { es: "Libro viejo.", zh: "旧书。" } },
      { es: "antiguo", zh: "古老的", example: { es: "Edificio antiguo.", zh: "古老建筑。" } },
      { es: "moderno", zh: "现代的", example: { es: "Arte moderno.", zh: "现代艺术。" } },
      { es: "joven", zh: "年轻的", example: { es: "Mujer joven.", zh: "年轻女人。" } },
      { es: "mayor", zh: "年长的", example: { es: "Hermano mayor.", zh: "哥哥。" } },
      { es: "menor", zh: "较小的", example: { es: "Hermano menor.", zh: "弟弟。" } },
      { es: "guapo", zh: "帅/漂亮", example: { es: "Niño guapo.", zh: "帅男孩。" } },
      { es: "bonito", zh: "漂亮的", example: { es: "Vestido bonito.", zh: "漂亮的裙子。" } },
      { es: "feo", zh: "丑的", example: { es: "Edificio feo.", zh: "丑建筑。" } },
      { es: "rico", zh: "富有的/美味", example: { es: "Comida rica.", zh: "美味。" } },
      { es: "pobre", zh: "贫穷的", example: { es: "País pobre.", zh: "穷国。" } },
      { es: "fuerte", zh: "强壮的", example: { es: "Hombre fuerte.", zh: "强壮的男人。" } },
      { es: "débil", zh: "虚弱的", example: { es: "Débil cuerpo.", zh: "虚弱的身体。" } },
      { es: "rápido", zh: "快的", example: { es: "Coche rápido.", zh: "快车。" } },
      { es: "lento", zh: "慢的", example: { es: "Tren lento.", zh: "慢车。" } },
      { es: "fácil", zh: "容易的", example: { es: "Examen fácil.", zh: "容易的考试。" } },
      { es: "difícil", zh: "困难的", example: { es: "Problema difícil.", zh: "难题。" } },
      { es: "duro", zh: "硬的/艰难的", example: { es: "Trabajo duro.", zh: "艰难的工作。" } },
      { es: "blando", zh: "软的", example: { es: "Almohada blanda.", zh: "软枕头。" } },
      { es: "caliente", zh: "热的", example: { es: "Agua caliente.", zh: "热水。" } },
      { es: "frío", zh: "冷的", example: { es: "Vino frío.", zh: "冷酒。" } },
      { es: "cálido", zh: "温暖的", example: { es: "Clima cálido.", zh: "温暖气候。" } },
      { es: "fresco", zh: "凉爽的/新鲜的", example: { es: "Aire fresco.", zh: "新鲜空气。" } },
      { es: "lluvioso", zh: "多雨的", example: { es: "Día lluvioso.", zh: "雨天。" } },
      { es: "seco", zh: "干的", example: { es: "Clima seco.", zh: "干燥气候。" } },
      { es: "húmedo", zh: "湿的", example: { es: "Clima húmedo.", zh: "潮湿气候。" } },
      { es: "limpio", zh: "干净的", example: { es: "Agua limpia.", zh: "干净的水。" } },
      { es: "sucio", zh: "脏的", example: { es: "Ropa sucia.", zh: "脏衣服。" } },
      { es: "nuevo", zh: "新的", example: { es: "Nueva casa.", zh: "新房子。" } },
      { es: "usado", zh: "用过的", example: { es: "Coche usado.", zh: "二手车。" } },
      { es: "lleno", zh: "满的", example: { es: "Taza llena.", zh: "满杯。" } },
      { es: "vacío", zh: "空的", example: { es: "Botella vacía.", zh: "空瓶。" } },
      { es: "abierto", zh: "开着的", example: { es: "Puerta abierta.", zh: "开着的门。" } },
      { es: "cerrado", zh: "关着的", example: { es: "Tienda cerrada.", zh: "关门的店。" } },
      { es: "primero", zh: "第一", example: { es: "El primer día.", zh: "第一天。" } },
      { es: "último", zh: "最后", example: { es: "La última vez.", zh: "最后一次。" } },
      { es: "siguiente", zh: "下一个", example: { es: "El siguiente.", zh: "下一个。" } },
      { es: "anterior", zh: "前一个", example: { es: "El día anterior.", zh: "前一天。" } },
      { es: "mismo", zh: "同样的", example: { es: "La misma cosa.", zh: "同样的事。" } },
      { es: "otro", zh: "另一个", example: { es: "Otro día.", zh: "改天。" } },
      { es: "todo", zh: "全部", example: { es: "Todo el mundo.", zh: "全世界。" } },
      { es: "nada", zh: "没有（东西）", example: { es: "Nada importante.", zh: "不重要。" } },
      { es: "mucho", zh: "很多", example: { es: "Mucho amor.", zh: "很多爱。" } },
      { es: "poco", zh: "很少", example: { es: "Poco tiempo.", zh: "很少时间。" } },
      { es: "demasiado", zh: "太多", example: { es: "Demasiado calor.", zh: "太热。" } },
      { es: "bastante", zh: "足够", example: { es: "Bastante comida.", zh: "足够食物。" } },
      { es: "más", zh: "更多", example: { es: "Más café.", zh: "更多咖啡。" } },
      { es: "menos", zh: "更少", example: { es: "Menos sal.", zh: "少盐。" } }
    ]
  },

  // ============ Unit 20: 天气自然 ============
  {
    id: 20, title: "天气自然", emoji: "☀️", color: "from-amber-300 to-orange-500", iconColor: "#FFC800",
    tip: "天气用 Hace + 名词：Hace calor (热)。Está + 形容词：Está soleado。",
    words: [
      { es: "tiempo", zh: "天气", example: { es: "Buen tiempo.", zh: "好天气。" } },
      { es: "clima", zh: "气候", example: { es: "Clima tropical.", zh: "热带气候。" } },
      { es: "sol", zh: "太阳", example: { es: "Hace sol.", zh: "出太阳。" } },
      { es: "luz", zh: "光", example: { es: "Luz del sol.", zh: "阳光。" } },
      { es: "lluvia", zh: "雨", example: { es: "Hay lluvia.", zh: "下雨。" } },
      { es: "llover", zh: "下雨", example: { es: "Va a llover.", zh: "要下雨了。" } },
      { es: "nieve", zh: "雪", example: { es: "Hay nieve.", zh: "下雪。" } },
      { es: "nevar", zh: "下雪", example: { es: "Va a nevar.", zh: "要下雪了。" } },
      { es: "viento", zh: "风", example: { es: "Hay viento.", zh: "有风。" } },
      { es: "calor", zh: "热", example: { es: "Hace calor.", zh: "天热。" } },
      { es: "frío", zh: "冷", example: { es: "Hace frío.", zh: "天冷。" } },
      { es: "nube", zh: "云", example: { es: "Nube blanca.", zh: "白云。" } },
      { es: "nublado", zh: "多云", example: { es: "Está nublado.", zh: "多云。" } },
      { es: "cielo", zh: "天空", example: { es: "Cielo azul.", zh: "蓝天。" } },
      { es: "tormenta", zh: "暴风雨", example: { es: "Tormenta fuerte.", zh: "强暴风雨。" } },
      { es: "trueno", zh: "雷", example: { es: "Trueno fuerte.", zh: "响雷。" } },
      { es: "relámpago", zh: "闪电", example: { es: "Relámpago brillante.", zh: "闪亮的闪电。" } },
      { es: "arco iris", zh: "彩虹", example: { es: "Arco iris bonito.", zh: "漂亮的彩虹。" } },
      { es: "estrella", zh: "星星", example: { es: "Estrella brillante.", zh: "闪亮的星。" } },
      { es: "luna", zh: "月亮", example: { es: "Luna llena.", zh: "满月。" } },
      { es: "tierra", zh: "地球/土地", example: { es: "La Tierra.", zh: "地球。" } },
      { es: "planeta", zh: "行星", example: { es: "Planeta Tierra.", zh: "地球行星。" } },
      { es: "río", zh: "河", example: { es: "Río grande.", zh: "大河。" } },
      { es: "lago", zh: "湖", example: { es: "Lago azul.", zh: "蓝湖。" } },
      { es: "mar", zh: "海", example: { es: "Mar azul.", zh: "蓝海。" } },
      { es: "océano", zh: "大洋", example: { es: "Océano Pacífico.", zh: "太平洋。" } },
      { es: "playa", zh: "海滩", example: { es: "Playa bonita.", zh: "漂亮海滩。" } },
      { es: "isla", zh: "岛", example: { es: "Isla tropical.", zh: "热带岛。" } },
      { es: "montaña", zh: "山", example: { es: "Montaña alta.", zh: "高山。" } },
      { es: "colina", zh: "小山", example: { es: "Colina verde.", zh: "绿色小山。" } },
      { es: "valle", zh: "山谷", example: { es: "Valle profundo.", zh: "深谷。" } },
      { es: "bosque", zh: "森林", example: { es: "Bosque denso.", zh: "密林。" } },
      { es: "selva", zh: "丛林", example: { es: "Selva tropical.", zh: "热带丛林。" } },
      { es: "desierto", zh: "沙漠", example: { es: "Desierto caliente.", zh: "热沙漠。" } },
      { es: "pradera", zh: "草原", example: { es: "Pradera verde.", zh: "绿草原。" } },
      { es: "campo", zh: "田野", example: { es: "Campo abierto.", zh: "开阔田野。" } },
      { es: "jardín", zh: "花园", example: { es: "Jardín bonito.", zh: "漂亮的花园。" } },
      { es: "flor", zh: "花", example: { es: "Flor roja.", zh: "红花。" } },
      { es: "rosa", zh: "玫瑰", example: { es: "Rosa roja.", zh: "红玫瑰。" } },
      { es: "girasol", zh: "向日葵", example: { es: "Girasol alto.", zh: "高向日葵。" } },
      { es: "árbol", zh: "树", example: { es: "Árbol grande.", zh: "大树。" } },
      { es: "hoja", zh: "叶子", example: { es: "Hoja verde.", zh: "绿叶。" } },
      { es: "piedra", zh: "石头", example: { es: "Piedra dura.", zh: "硬石头。" } },
      { es: "arena", zh: "沙子", example: { es: "Arena blanca.", zh: "白沙。" } },
      { es: "fuego", zh: "火", example: { es: "Fuego caliente.", zh: "热火。" } },
      { es: "agua", zh: "水", example: { es: "Agua clara.", zh: "清水。" } },
      { es: "aire", zh: "空气", example: { es: "Aire fresco.", zh: "新鲜空气。" } },
      { es: "estación", zh: "季节", example: { es: "Las cuatro estaciones.", zh: "四季。" } },
      { es: "primavera", zh: "春天", example: { es: "Primavera florida.", zh: "花开的春天。" } },
      { es: "verano", zh: "夏天", example: { es: "Verano caluroso.", zh: "炎热的夏天。" } },
      { es: "otoño", zh: "秋天", example: { es: "Otoño dorado.", zh: "金色的秋天。" } },
      { es: "invierno", zh: "冬天", example: { es: "Invierno frío.", zh: "寒冷的冬天。" } }
    ]
  },

  // ============ Unit 21: 常用动词 ============
  {
    id: 21, title: "常用动词", emoji: "🏃", color: "from-rose-500 to-red-600", iconColor: "#FF4B4B",
    tip: "西语动词按主语变位：yo hablo, tú hablas, él habla。-ar 结尾规则动词最常见。",
    words: [
      { es: "ser", zh: "是（本质）", example: { es: "Yo soy Ana.", zh: "我是安娜。" } },
      { es: "estar", zh: "是（状态/位置）", example: { es: "Estoy en casa.", zh: "我在家。" } },
      { es: "tener", zh: "有", example: { es: "Tengo un libro.", zh: "我有一本书。" } },
      { es: "hacer", zh: "做", example: { es: "Hago la tarea.", zh: "我做作业。" } },
      { es: "ir", zh: "去", example: { es: "Voy al colegio.", zh: "我去学校。" } },
      { es: "venir", zh: "来", example: { es: "Ven a mi casa.", zh: "来我家。" } },
      { es: "ver", zh: "看", example: { es: "Veo una película.", zh: "我看电影。" } },
      { es: "comer", zh: "吃", example: { es: "Como una manzana.", zh: "我吃苹果。" } },
      { es: "beber", zh: "喝", example: { es: "Bebo agua.", zh: "我喝水。" } },
      { es: "hablar", zh: "说/讲", example: { es: "Hablo español.", zh: "我说西语。" } },
      { es: "escuchar", zh: "听", example: { es: "Escucho música.", zh: "我听音乐。" } },
      { es: "leer", zh: "读", example: { es: "Leo un libro.", zh: "我读书。" } },
      { es: "escribir", zh: "写", example: { es: "Escribo una carta.", zh: "我写信。" } },
      { es: "estudiar", zh: "学习", example: { es: "Estudio mucho.", zh: "我用功学。" } },
      { es: "aprender", zh: "学（会）", example: { es: "Aprendo español.", zh: "我学西语。" } },
      { es: "enseñar", zh: "教", example: { es: "Enseño a niños.", zh: "我教孩子。" } },
      { es: "jugar", zh: "玩", example: { es: "Juego al fútbol.", zh: "我踢足球。" } },
      { es: "trabajar", zh: "工作", example: { es: "Trabajo en una oficina.", zh: "我在办公室工作。" } },
      { es: "vivir", zh: "住/生活", example: { es: "Vivo en Madrid.", zh: "我住在马德里。" } },
      { es: "dormir", zh: "睡觉", example: { es: "Duermo ocho horas.", zh: "我睡八小时。" } },
      { es: "despertar", zh: "醒来", example: { es: "Me despierto temprano.", zh: "我醒得早。" } },
      { es: "levantarse", zh: "起床", example: { es: "Me levanto a las 7.", zh: "我七点起床。" } },
      { es: "caminar", zh: "走路", example: { es: "Camino al colegio.", zh: "我走到学校。" } },
      { es: "correr", zh: "跑步", example: { es: "Corro en el parque.", zh: "我在公园跑步。" } },
      { es: "nadar", zh: "游泳", example: { es: "Nado en la piscina.", zh: "我在泳池游。" } },
      { es: "comprar", zh: "买", example: { es: "Compro pan.", zh: "我买面包。" } },
      { es: "vender", zh: "卖", example: { es: "Vendo mi coche.", zh: "我卖我的车。" } },
      { es: "pagar", zh: "付款", example: { es: "Pago con tarjeta.", zh: "我刷卡付。" } },
      { es: "cocinar", zh: "做饭", example: { es: "Cocino pasta.", zh: "我煮意面。" } },
      { es: "limpiar", zh: "打扫", example: { es: "Limpio mi cuarto.", zh: "我打扫房间。" } },
      { es: "lavar", zh: "洗", example: { es: "Lavo los platos.", zh: "我洗碗。" } },
      { es: "abrir", zh: "打开", example: { es: "Abro la puerta.", zh: "我开门。" } },
      { es: "cerrar", zh: "关闭", example: { es: "Cierro la ventana.", zh: "我关窗。" } },
      { es: "entrar", zh: "进入", example: { es: "Entro en la clase.", zh: "我进教室。" } },
      { es: "salir", zh: "出去", example: { es: "Salgo a las 5.", zh: "我五点出去。" } },
      { es: "llegar", zh: "到达", example: { es: "Llego a casa.", zh: "我到家了。" } },
      { es: "volver", zh: "回来", example: { es: "Vuelvo mañana.", zh: "我明天回来。" } },
      { es: "buscar", zh: "找", example: { es: "Busco mis llaves.", zh: "我找钥匙。" } },
      { es: "encontrar", zh: "找到", example: { es: "Encuentro el libro.", zh: "我找到书。" } },
      { es: "perder", zh: "丢失", example: { es: "Pierdo mi tiempo.", zh: "我浪费时间。" } },
      { es: "conducir", zh: "驾驶", example: { es: "Conduzco el coche.", zh: "我开车。" } },
      { es: "nadar", zh: "游泳", example: { es: "Nado en el mar.", zh: "我在海里游。" } },
      { es: "querer", zh: "想要/爱", example: { es: "Te quiero.", zh: "我爱你。" } },
      { es: "poder", zh: "能", example: { es: "Puedo ayudar.", zh: "我能帮忙。" } },
      { es: "deber", zh: "应该", example: { es: "Debo estudiar.", zh: "我应该学习。" } },
      { es: "saber", zh: "知道（事实）", example: { es: "Sé la respuesta.", zh: "我知道答案。" } },
      { es: "conocer", zh: "认识（人/地）", example: { es: "Conozco a Ana.", zh: "我认识安娜。" } },
      { es: "pensar", zh: "想/思考", example: { es: "Pienso en ti.", zh: "我想你。" } },
      { es: "creer", zh: "相信", example: { es: "Creo en ti.", zh: "我相信你。" } },
      { es: "esperar", zh: "等待/希望", example: { es: "Te espero.", zh: "我等你。" } },
      { es: "mirar", zh: "看", example: { es: "Mira esto.", zh: "看这个。" } },
      { es: "buscar", zh: "寻找", example: { es: "Busco un libro.", zh: "我找书。" } },
      { es: "ayudar", zh: "帮助", example: { es: "Ayudo a mamá.", zh: "我帮妈妈。" } },
      { es: "amar", zh: "爱", example: { es: "Amo a mi familia.", zh: "我爱我家。" } },
      { es: "odiar", zh: "恨", example: { es: "Odio las espinacas.", zh: "我讨厌菠菜。" } },
      { es: "temer", zh: "害怕", example: { es: "Temo a la oscuridad.", zh: "我怕黑。" } },
      { es: "reír", zh: "笑", example: { es: "Río mucho.", zh: "我笑得多。" } },
      { es: "llorar", zh: "哭", example: { es: "Lloro de alegría.", zh: "我高兴得哭。" } },
      { es: "gritar", zh: "喊叫", example: { es: "Grito fuerte.", zh: "我大声喊。" } },
      { es: "callar", zh: "安静", example: { es: "¡Cállate!", zh: "安静！" } },
      { es: "decir", zh: "说", example: { es: "Digo la verdad.", zh: "我说实话。" } },
      { es: "hablar", zh: "说话", example: { es: "Hablo por teléfono.", zh: "我打电话。" } },
      { es: "preguntar", zh: "问", example: { es: "Pregunto al profesor.", zh: "我问老师。" } },
      { es: "responder", zh: "回答", example: { es: "Respondo la pregunta.", zh: "我回答问题。" } },
      { es: "contestar", zh: "回答", example: { es: "Contesto el teléfono.", zh: "我接电话。" } }
    ]
  },

  // ============ Unit 22: 介词与连词 ============
  {
    id: 22, title: "介词连词", emoji: "🔗", color: "from-gray-400 to-gray-600", iconColor: "#1CB0F6",
    tip: "a (到/在), de (的/从), en (在/里), con (和/用), sin (没有/无), para (为了), por (因为/经过)。",
    words: [
      { es: "a", zh: "到/在", example: { es: "Voy a casa.", zh: "我回家。" } },
      { es: "de", zh: "的/从", example: { es: "El libro de Ana.", zh: "安娜的书。" } },
      { es: "en", zh: "在/里", example: { es: "Estoy en casa.", zh: "我在家。" } },
      { es: "con", zh: "和/用", example: { es: "Vengo con mi amigo.", zh: "我和朋友来。" } },
      { es: "sin", zh: "没有/无", example: { es: "Sin azúcar.", zh: "不加糖。" } },
      { es: "para", zh: "为了/给", example: { es: "Para ti.", zh: "给你的。" } },
      { es: "por", zh: "因为/经过", example: { es: "Por la mañana.", zh: "在早上。" } },
      { es: "sobre", zh: "在...上/关于", example: { es: "Sobre la mesa.", zh: "在桌上。" } },
      { es: "bajo", zh: "在...下", example: { es: "Bajo la cama.", zh: "在床下。" } },
      { es: "entre", zh: "在...之间", example: { es: "Entre amigos.", zh: "朋友之间。" } },
      { es: "hasta", zh: "直到", example: { es: "Hasta mañana.", zh: "直到明天。" } },
      { es: "desde", zh: "自从/从", example: { es: "Desde ayer.", zh: "从昨天起。" } },
      { es: "hacia", zh: "向/朝", example: { es: "Hacia el norte.", zh: "向北。" } },
      { es: "durante", zh: "在...期间", example: { es: "Durante el día.", zh: "白天期间。" } },
      { es: "antes de", zh: "在...之前", example: { es: "Antes de comer.", zh: "饭前。" } },
      { es: "después de", zh: "在...之后", example: { es: "Después de clase.", zh: "课后。" } },
      { es: "y", zh: "和", example: { es: "Tú y yo.", zh: "你和我。" } },
      { es: "o", zh: "或", example: { es: "¿Sí o no?", zh: "是还是不是？" } },
      { es: "pero", zh: "但是", example: { es: "Quiero, pero no puedo.", zh: "我想，但不能。" } },
      { es: "porque", zh: "因为", example: { es: "Porque sí.", zh: "因为是的。" } },
      { es: "si", zh: "如果", example: { es: "Si quieres.", zh: "如果你想。" } },
      { es: "cuando", zh: "当...时", example: { es: "Cuando llegue.", zh: "当他到时。" } },
      { es: "como", zh: "像/如何", example: { es: "Como tú.", zh: "像你一样。" } },
      { es: "que", zh: "那/的", example: { es: "Sé que vienes.", zh: "我知道你来。" } },
      { es: "muy", zh: "非常", example: { es: "Muy bien.", zh: "非常好。" } },
      { es: "mucho", zh: "很/多", example: { es: "Te quiero mucho.", zh: "我非常爱你。" } },
      { es: "poco", zh: "少/一点", example: { es: "Un poco.", zh: "一点。" } },
      { es: "más", zh: "更", example: { es: "Más o menos.", zh: "或多或少。" } },
      { es: "menos", zh: "更少", example: { es: "Menos mal.", zh: "还好。" } },
      { es: "tan", zh: "如此", example: { es: "Tan bonito.", zh: "这么漂亮。" } },
      { es: "tanto", zh: "这么多", example: { es: "Tanto como.", zh: "和...一样多。" } },
      { es: "aquí", zh: "这里", example: { es: "Aquí estoy.", zh: "我在这里。" } },
      { es: "allí", zh: "那里", example: { es: "Allí está.", zh: "在那里。" } },
      { es: "ahí", zh: "那里（中距）", example: { es: "Por ahí.", zh: "在那边。" } }
    ]
  },

  // ============ Unit 23: 情感表达 ============
  {
    id: 23, title: "情感表达", emoji: "😊", color: "from-yellow-300 to-pink-500", iconColor: "#FFC800",
    tip: "情感形容词男女同形。常用 Estar + 形容词（暂时状态）或 Ser + 形容词（性格）。",
    words: [
      { es: "feliz", zh: "开心", example: { es: "Estoy feliz.", zh: "我很开心。" } },
      { es: "alegre", zh: "快乐", example: { es: "Día alegre.", zh: "快乐的一天。" } },
      { es: "contento", zh: "高兴", example: { es: "Estoy contento.", zh: "我高兴。" } },
      { es: "triste", zh: "悲伤", example: { es: "Estoy triste.", zh: "我难过。" } },
      { es: "enojado", zh: "生气", example: { es: "Está enojado.", zh: "他生气。" } },
      { es: "enfadado", zh: "生气（西）", example: { es: "Estoy enfadado.", zh: "我生气。" } },
      { es: "enfermo", zh: "生病的", example: { es: "Estoy enfermo.", zh: "我生病了。" } },
      { es: "cansado", zh: "累的", example: { es: "Estoy cansado.", zh: "我累了。" } },
      { es: "preocupado", zh: "担心的", example: { es: "Estoy preocupado.", zh: "我担心。" } },
      { es: "nervioso", zh: "紧张的", example: { es: "Estoy nervioso.", zh: "我紧张。" } },
      { es: "tranquilo", zh: "平静的", example: { es: "Estoy tranquilo.", zh: "我平静。" } },
      { es: "relajado", zh: "放松的", example: { es: "Estoy relajado.", zh: "我放松。" } },
      { es: "sorprendido", zh: "惊讶的", example: { es: "Estoy sorprendido.", zh: "我惊讶。" } },
      { es: "asustado", zh: "害怕的", example: { es: "Estoy asustado.", zh: "我害怕。" } },
      { es: "avergonzado", zh: "尴尬的", example: { es: "Estoy avergonzado.", zh: "我尴尬。" } },
      { es: "orgulloso", zh: "骄傲的", example: { es: "Estoy orgulloso.", zh: "我骄傲。" } },
      { es: "aburrido", zh: "无聊的", example: { es: "Estoy aburrido.", zh: "我无聊。" } },
      { es: "interesado", zh: "感兴趣的", example: { es: "Estoy interesado.", zh: "我感兴趣。" } },
      { es: "emocionado", zh: "激动的", example: { es: "Estoy emocionado.", zh: "我激动。" } },
      { es: "celoso", zh: "嫉妒的", example: { es: "Está celoso.", zh: "他嫉妒。" } },
      { es: "solo", zh: "孤独的", example: { es: "Me siento solo.", zh: "我感到孤独。" } },
      { es: "amor", zh: "爱", example: { es: "Mucho amor.", zh: "很多爱。" } },
      { es: "odio", zh: "恨", example: { es: "Odio las arañas.", zh: "我讨厌蜘蛛。" } },
      { es: "miedo", zh: "害怕", example: { es: "Tengo miedo.", zh: "我害怕。" } },
      { es: "alegría", zh: "喜悦", example: { es: "Lleno de alegría.", zh: "充满喜悦。" } },
      { es: "tristeza", zh: "悲伤", example: { es: "Con tristeza.", zh: "带着悲伤。" } },
      { es: "enojo", zh: "生气", example: { es: "Enojo grande.", zh: "大怒。" } },
      { es: "sorpresa", zh: "惊讶", example: { es: "¡Qué sorpresa!", zh: "好惊讶！" } },
      { es: "emoción", zh: "激动", example: { es: "Gran emoción.", zh: "激动不已。" } },
      { es: "esperanza", zh: "希望", example: { es: "Con esperanza.", zh: "带着希望。" } },
      { es: "sueño", zh: "梦想", example: { es: "Mi sueño.", zh: "我的梦想。" } },
      { es: "risa", zh: "笑", example: { es: "Risa fuerte.", zh: "大笑。" } },
      { es: "llanto", zh: "哭", example: { es: "Llanto triste.", zh: "悲伤的哭。" } },
      { es: "sonrisa", zh: "微笑", example: { es: "Bonita sonrisa.", zh: "漂亮的微笑。" } },
      { es: "lágrima", zh: "眼泪", example: { es: "Una lágrima.", zh: "一滴泪。" } },
      { es: "corazón", zh: "心", example: { es: "Corazón roto.", zh: "心碎。" } },
      { es: "alma", zh: "灵魂", example: { es: "Alma gemela.", zh: "灵魂伴侣。" } }
    ]
  },

  // ============ Unit 24: 节日文化 ============
  {
    id: 24, title: "节日文化", emoji: "🎉", color: "from-red-400 to-pink-600", iconColor: "#FF4B4B",
    tip: "西语国家重要节日：Navidad, Año Nuevo, Día de los Muertos, Semana Santa。",
    words: [
      { es: "fiesta", zh: "节日/派对", example: { es: "Fiesta grande.", zh: "大派对。" } },
      { es: "celebración", zh: "庆典", example: { es: "Gran celebración.", zh: "大庆典。" } },
      { es: "Navidad", zh: "圣诞节", example: { es: "¡Feliz Navidad!", zh: "圣诞快乐！" } },
      { es: "Año Nuevo", zh: "新年", example: { es: "¡Feliz Año Nuevo!", zh: "新年快乐！" } },
      { es: "cumpleaños", zh: "生日", example: { es: "¡Feliz cumpleaños!", zh: "生日快乐！" } },
      { es: "boda", zh: "婚礼", example: { es: "Boda bonita.", zh: "漂亮的婚礼。" } },
      { es: "Pascua", zh: "复活节", example: { es: "Feliz Pascua.", zh: "复活节快乐。" } },
      { es: "Semana Santa", zh: "圣周", example: { es: "Semana Santa.", zh: "圣周。" } },
      { es: "Carnaval", zh: "狂欢节", example: { es: "Carnaval de Río.", zh: "里约狂欢节。" } },
      { es: "Día de los Muertos", zh: "亡灵节", example: { es: "Día de los Muertos.", zh: "亡灵节。" } },
      { es: "Halloween", zh: "万圣节", example: { es: "Halloween divertido.", zh: "有趣的万圣节。" } },
      { es: "Día de San Valentín", zh: "情人节", example: { es: "San Valentín.", zh: "情人节。" } },
      { es: "Día de la Madre", zh: "母亲节", example: { es: "Día de la Madre.", zh: "母亲节。" } },
      { es: "Día del Padre", zh: "父亲节", example: { es: "Día del Padre.", zh: "父亲节。" } },
      { es: "Día de la Independencia", zh: "独立日", example: { es: "Día de Independencia.", zh: "独立日。" } },
      { es: "regalo", zh: "礼物", example: { es: "Un regalo.", zh: "一个礼物。" } },
      { es: "obsequio", zh: "礼物（书）", example: { es: "Obsequio especial.", zh: "特别礼物。" } },
      { es: "invitado", zh: "客人", example: { es: "Los invitados.", zh: "客人们。" } },
      { es: "fiesta", zh: "派对", example: { es: "Fiesta sorpresa.", zh: "惊喜派对。" } },
      { es: "celebrar", zh: "庆祝", example: { es: "Celebramos juntos.", zh: "我们一起庆祝。" } },
      { es: "felicitar", zh: "祝贺", example: { es: "Te felicito.", zh: "恭喜你。" } },
      { es: "invitar", zh: "邀请", example: { es: "Te invito.", zh: "我请你。" } },
      { es: "brindar", zh: "敬酒", example: { es: "Brindamos por ti.", zh: "为你干杯。" } },
      { es: "salud", zh: "健康/干杯", example: { es: "¡Salud!", zh: "干杯！" } },
      { es: "felicidad", zh: "幸福", example: { es: "Mucha felicidad.", zh: "很多幸福。" } },
      { es: "suerte", zh: "运气", example: { es: "Buena suerte.", zh: "好运。" } },
      { es: "éxito", zh: "成功", example: { es: "Mucho éxito.", zh: "大成功。" } },
      { es: "tradición", zh: "传统", example: { es: "Tradición familiar.", zh: "家庭传统。" } },
      { es: "costumbre", zh: "习俗", example: { es: "Costumbre local.", zh: "当地习俗。" } },
      { es: "cultura", zh: "文化", example: { es: "Cultura rica.", zh: "丰富的文化。" } },
      { es: "historia", zh: "历史", example: { es: "Historia antigua.", zh: "古代历史。" } },
      { es: "país", zh: "国家", example: { es: "Mi país.", zh: "我的国家。" } },
      { es: "España", zh: "西班牙", example: { es: "España es bonita.", zh: "西班牙很美。" } },
      { es: "México", zh: "墨西哥", example: { es: "México lindo.", zh: "美丽的墨西哥。" } },
      { es: "Argentina", zh: "阿根廷", example: { es: "Argentina grande.", zh: "大阿根廷。" } },
      { es: "Colombia", zh: "哥伦比亚", example: { es: "Colombia rica.", zh: "丰富的哥伦比亚。" } },
      { es: "Perú", zh: "秘鲁", example: { es: "Perú antiguo.", zh: "古老秘鲁。" } },
      { es: "Chile", zh: "智利", example: { es: "Chile largo.", zh: "狭长的智利。" } },
      { es: "idioma", zh: "语言", example: { es: "El español es un idioma.", zh: "西语是门语言。" } },
      { es: "lengua", zh: "语言/舌头", example: { es: "Lengua materna.", zh: "母语。" } }
    ]
  },

  // ============ Unit 25: 常用短语 ============
  {
    id: 25, title: "常用短语", emoji: "💬", color: "from-indigo-400 to-purple-600", iconColor: "#CE82FF",
    tip: "短语是日常对话的骨架。记住完整短语比单独记单词更实用！",
    words: [
      { es: "¿Cómo estás?", zh: "你好吗？", example: { es: "¿Cómo estás hoy?", zh: "今天怎么样？" } },
      { es: "Estoy bien", zh: "我很好", example: { es: "Estoy bien, gracias.", zh: "我很好，谢谢。" } },
      { es: "No entiendo", zh: "我不懂", example: { es: "No entiendo.", zh: "我不懂。" } },
      { es: "¿Puedes repetir?", zh: "你能重复吗？", example: { es: "¿Puedes repetir?", zh: "你能重复吗？" } },
      { es: "¿Qué significa?", zh: "什么意思？", example: { es: "¿Qué significa?", zh: "什么意思？" } },
      { es: "No sé", zh: "我不知道", example: { es: "No sé.", zh: "我不知道。" } },
      { es: "Tengo una pregunta", zh: "我有个问题", example: { es: "Tengo una pregunta.", zh: "我有个问题。" } },
      { es: "Por favor", zh: "请", example: { es: "Por favor.", zh: "请。" } },
      { es: "Disculpe", zh: "打扰了", example: { es: "Disculpe, ¿la salida?", zh: "打扰了，出口在哪？" } },
      { es: "Con permiso", zh: "借过", example: { es: "Con permiso.", zh: "借过。" } },
      { es: "Mucho gusto", zh: "幸会", example: { es: "Mucho gusto.", zh: "幸会。" } },
      { es: "Te presento a", zh: "我介绍你认识", example: { es: "Te presento a Ana.", zh: "我介绍你认识安娜。" } },
      { es: "¡Ayuda!", zh: "救命！", example: { es: "¡Ayuda!", zh: "救命！" } },
      { es: "¡Cuidado!", zh: "小心！", example: { es: "¡Cuidado!", zh: "小心！" } },
      { es: "¡Vamos!", zh: "走吧！", example: { es: "¡Vamos!", zh: "走吧！" } },
      { es: "¡Corre!", zh: "快跑！", example: { es: "¡Corre!", zh: "快跑！" } },
      { es: "¡Espera!", zh: "等等！", example: { es: "¡Espera!", zh: "等等！" } },
      { es: "¡Ya voy!", zh: "我来了！", example: { es: "¡Ya voy!", zh: "我来了！" } },
      { es: "¿Adónde vas?", zh: "你去哪？", example: { es: "¿Adónde vas?", zh: "你去哪？" } },
      { es: "Voy a casa", zh: "我回家", example: { es: "Voy a casa.", zh: "我回家。" } },
      { es: "Tengo hambre", zh: "我饿了", example: { es: "Tengo hambre.", zh: "我饿了。" } },
      { es: "Tengo sed", zh: "我渴了", example: { es: "Tengo sed.", zh: "我渴了。" } },
      { es: "Tengo sueño", zh: "我困了", example: { es: "Tengo sueño.", zh: "我困了。" } },
      { es: "Tengo frío", zh: "我冷", example: { es: "Tengo frío.", zh: "我冷。" } },
      { es: "Tengo calor", zh: "我热", example: { es: "Tengo calor.", zh: "我热。" } },
      { es: "Me duele", zh: "我疼", example: { es: "Me duele la cabeza.", zh: "我头疼。" } },
      { es: "¿Qué hora es?", zh: "几点了？", example: { es: "¿Qué hora es?", zh: "几点了？" } },
      { es: "¿Cuánto cuesta?", zh: "多少钱？", example: { es: "¿Cuánto cuesta?", zh: "多少钱？" } },
      { es: "¿Dónde está?", zh: "在哪里？", example: { es: "¿Dónde está el baño?", zh: "洗手间在哪？" } },
      { es: "¿Cómo se dice?", zh: "这个怎么说？", example: { es: "¿Cómo se dice?", zh: "这个怎么说？" } },
      { es: "Más despacio", zh: "慢一点", example: { es: "Más despacio, por favor.", zh: "请慢一点。" } },
      { es: "Lo mismo", zh: "同样的", example: { es: "Lo mismo para mí.", zh: "我也一样。" } },
      { es: "La cuenta, por favor", zh: "买单", example: { es: "La cuenta, por favor.", zh: "请买单。" } },
      { es: "Está delicioso", zh: "很好吃", example: { es: "¡Está delicioso!", zh: "很好吃！" } },
      { es: "Tengo prisa", zh: "我赶时间", example: { es: "Tengo prisa.", zh: "我赶时间。" } },
      { es: "Hasta la vista", zh: "回头见", example: { es: "Hasta la vista.", zh: "回头见。" } },
      { es: "Que descanses", zh: "好好休息", example: { es: "Que descanses.", zh: "好好休息。" } },
      { es: "Que te vaya bien", zh: "祝你一切顺利", example: { es: "Que te vaya bien.", zh: "祝你一切顺利。" } },
      { es: "Buen provecho", zh: "祝你好胃口", example: { es: "¡Buen provecho!", zh: "祝你好胃口！" } },
      { es: "Salud", zh: "保重/干杯", example: { es: "¡Salud!", zh: "干杯！" } },
      { es: "¡Felicidades!", zh: "恭喜！", example: { es: "¡Felicidades!", zh: "恭喜！" } },
      { es: "¡Bien hecho!", zh: "做得好！", example: { es: "¡Bien hecho!", zh: "做得好！" } },
      { es: "¡Ánimo!", zh: "加油！", example: { es: "¡Ánimo!", zh: "加油！" } },
      { es: "¡Genial!", zh: "太棒了！", example: { es: "¡Genial!", zh: "太棒了！" } },
      { es: "¡Increíble!", zh: "不可思议！", example: { es: "¡Increíble!", zh: "不可思议！" } },
      { es: "¡Qué lástima!", zh: "太可惜了！", example: { es: "¡Qué lástima!", zh: "太可惜了！" } },
      { es: "¡Qué aburrido!", zh: "真无聊！", example: { es: "¡Qué aburrido!", zh: "真无聊！" } },
      { es: "¡Qué rica!", zh: "真好吃！", example: { es: "¡Qué rica la comida!", zh: "饭真好吃！" } }
    ]
  }
];

// 词汇库完成：25 单元，1300+ 词
